// GENERATED by apps/macos/lucide-gen.py from crates/adi-ui/icons/*.svg — do not edit.
// Regenerate with `python3 apps/macos/lucide-gen.py`. Lucide 1.39.0, ISC licence
// (crates/adi-ui/icons/LICENSE). The same file is written to both native apps.

import SwiftUI

/// One Lucide icon, by its lucide.dev name (`design/DESIGN.md` §9). The only icon library in the
/// product; nothing here draws its own glyph and nothing uses SF Symbols.
enum Lucide: String, CaseIterable {
    case arrowUp = "arrow-up"
    case arrowUpRight = "arrow-up-right"
    case bug = "bug"
    case camera = "camera"
    case check = "check"
    case chevronRight = "chevron-right"
    case circleAlert = "circle-alert"
    case clipboard = "clipboard"
    case code = "code"
    case copy = "copy"
    case ellipsis = "ellipsis"
    case globe = "globe"
    case info = "info"
    case keyRound = "key-round"
    case layoutDashboard = "layout-dashboard"
    case layoutGrid = "layout-grid"
    case link = "link"
    case monitor = "monitor"
    case network = "network"
    case plus = "plus"
    case power = "power"
    case qrCode = "qr-code"
    case radio = "radio"
    case scanLine = "scan-line"
    case settings2 = "settings-2"
    case share = "share"
    case triangleAlert = "triangle-alert"
    case x = "x"

    /// The inside of the icon's `<svg>`, on Lucide's 24×24 grid.
    var markup: String {
        switch self {
        case .arrowUp: "<path d=\"m5 12 7-7 7 7\" /><path d=\"M12 19V5\" />"
        case .arrowUpRight: "<path d=\"M7 7h10v10\" /><path d=\"M7 17 17 7\" />"
        case .bug: "<path d=\"M12 20v-9\" /><path d=\"M14 7a4 4 0 0 1 4 4v3a6 6 0 0 1-12 0v-3a4 4 0 0 1 4-4z\" /><path d=\"M14.12 3.88 16 2\" /><path d=\"M21 21a4 4 0 0 0-3.81-4\" /><path d=\"M21 5a4 4 0 0 1-3.55 3.97\" /><path d=\"M22 13h-4\" /><path d=\"M3 21a4 4 0 0 1 3.81-4\" /><path d=\"M3 5a4 4 0 0 0 3.55 3.97\" /><path d=\"M6 13H2\" /><path d=\"m8 2 1.88 1.88\" /><path d=\"M9 7.13V6a3 3 0 1 1 6 0v1.13\" />"
        case .camera: "<path d=\"M13.997 4a2 2 0 0 1 1.76 1.05l.486.9A2 2 0 0 0 18.003 7H20a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h1.997a2 2 0 0 0 1.759-1.048l.489-.904A2 2 0 0 1 10.004 4z\" /><circle cx=\"12\" cy=\"13\" r=\"3\" />"
        case .check: "<path d=\"M20 6 9 17l-5-5\" />"
        case .chevronRight: "<path d=\"m9 18 6-6-6-6\" />"
        case .circleAlert: "<circle cx=\"12\" cy=\"12\" r=\"10\" /><line x1=\"12\" x2=\"12\" y1=\"8\" y2=\"12\" /><line x1=\"12\" x2=\"12.01\" y1=\"16\" y2=\"16\" />"
        case .clipboard: "<rect width=\"8\" height=\"4\" x=\"8\" y=\"2\" rx=\"1\" ry=\"1\" /><path d=\"M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2\" />"
        case .code: "<path d=\"m16 18 6-6-6-6\" /><path d=\"m8 6-6 6 6 6\" />"
        case .copy: "<rect width=\"14\" height=\"14\" x=\"8\" y=\"8\" rx=\"2\" ry=\"2\" /><path d=\"M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2\" />"
        case .ellipsis: "<circle cx=\"12\" cy=\"12\" r=\"1\" /><circle cx=\"19\" cy=\"12\" r=\"1\" /><circle cx=\"5\" cy=\"12\" r=\"1\" />"
        case .globe: "<circle cx=\"12\" cy=\"12\" r=\"10\" /><path d=\"M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20\" /><path d=\"M2 12h20\" />"
        case .info: "<circle cx=\"12\" cy=\"12\" r=\"10\" /><path d=\"M12 16v-4\" /><path d=\"M12 8h.01\" />"
        case .keyRound: "<path d=\"M2.586 17.414A2 2 0 0 0 2 18.828V21a1 1 0 0 0 1 1h3a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h1a1 1 0 0 0 1-1v-1a1 1 0 0 1 1-1h.172a2 2 0 0 0 1.414-.586l.814-.814a6.5 6.5 0 1 0-4-4z\" /><circle cx=\"16.5\" cy=\"7.5\" r=\".5\" fill=\"currentColor\" />"
        case .layoutDashboard: "<rect width=\"7\" height=\"9\" x=\"3\" y=\"3\" rx=\"1\" /><rect width=\"7\" height=\"5\" x=\"14\" y=\"3\" rx=\"1\" /><rect width=\"7\" height=\"9\" x=\"14\" y=\"12\" rx=\"1\" /><rect width=\"7\" height=\"5\" x=\"3\" y=\"16\" rx=\"1\" />"
        case .layoutGrid: "<rect width=\"7\" height=\"7\" x=\"3\" y=\"3\" rx=\"1\" /><rect width=\"7\" height=\"7\" x=\"14\" y=\"3\" rx=\"1\" /><rect width=\"7\" height=\"7\" x=\"14\" y=\"14\" rx=\"1\" /><rect width=\"7\" height=\"7\" x=\"3\" y=\"14\" rx=\"1\" />"
        case .link: "<path d=\"M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71\" /><path d=\"M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71\" />"
        case .monitor: "<rect width=\"20\" height=\"14\" x=\"2\" y=\"3\" rx=\"2\" /><line x1=\"8\" x2=\"16\" y1=\"21\" y2=\"21\" /><line x1=\"12\" x2=\"12\" y1=\"17\" y2=\"21\" />"
        case .network: "<rect x=\"16\" y=\"16\" width=\"6\" height=\"6\" rx=\"1\" /><rect x=\"2\" y=\"16\" width=\"6\" height=\"6\" rx=\"1\" /><rect x=\"9\" y=\"2\" width=\"6\" height=\"6\" rx=\"1\" /><path d=\"M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3\" /><path d=\"M12 12V8\" />"
        case .plus: "<path d=\"M5 12h14\" /><path d=\"M12 5v14\" />"
        case .power: "<path d=\"M12 2v10\" /><path d=\"M18.4 6.6a9 9 0 1 1-12.77.04\" />"
        case .qrCode: "<rect width=\"5\" height=\"5\" x=\"3\" y=\"3\" rx=\"1\" /><rect width=\"5\" height=\"5\" x=\"16\" y=\"3\" rx=\"1\" /><rect width=\"5\" height=\"5\" x=\"3\" y=\"16\" rx=\"1\" /><path d=\"M21 16h-3a2 2 0 0 0-2 2v3\" /><path d=\"M21 21v.01\" /><path d=\"M12 7v3a2 2 0 0 1-2 2H7\" /><path d=\"M3 12h.01\" /><path d=\"M12 3h.01\" /><path d=\"M12 16v.01\" /><path d=\"M16 12h1\" /><path d=\"M21 12v.01\" /><path d=\"M12 21v-1\" />"
        case .radio: "<path d=\"M16.247 7.761a6 6 0 0 1 0 8.478\" /><path d=\"M19.075 4.933a10 10 0 0 1 0 14.134\" /><path d=\"M4.925 19.067a10 10 0 0 1 0-14.134\" /><path d=\"M7.753 16.239a6 6 0 0 1 0-8.478\" /><circle cx=\"12\" cy=\"12\" r=\"2\" />"
        case .scanLine: "<path d=\"M3 7V5a2 2 0 0 1 2-2h2\" /><path d=\"M17 3h2a2 2 0 0 1 2 2v2\" /><path d=\"M21 17v2a2 2 0 0 1-2 2h-2\" /><path d=\"M7 21H5a2 2 0 0 1-2-2v-2\" /><path d=\"M7 12h10\" />"
        case .settings2: "<path d=\"M14 17H5\" /><path d=\"M19 7h-9\" /><circle cx=\"17\" cy=\"17\" r=\"3\" /><circle cx=\"7\" cy=\"7\" r=\"3\" />"
        case .share: "<path d=\"M12 2v13\" /><path d=\"m16 6-4-4-4 4\" /><path d=\"M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8\" />"
        case .triangleAlert: "<path d=\"m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3\" /><path d=\"M12 9v4\" /><path d=\"M12 17h.01\" />"
        case .x: "<path d=\"M18 6 6 18\" /><path d=\"m6 6 12 12\" />"
        }
    }
}

/// The four sizes an icon may be (§9). Nothing else.
enum LucideSize: CGFloat {
    /// Inside list-item meta and tags.
    case sm = 14
    /// Tree and explorer rows, table cells, buttons, panel headers. The default.
    case md = 16
    /// Feature blocks.
    case lg = 20
    /// Empty states only.
    case xl = 24
}

/// An icon, drawn the one way §9 allows: stroke 1.5 on the 24 grid, round caps and joins, in the
/// colour of the text beside it (`foregroundStyle`). Hidden from assistive technology unless given
/// a `label`, because an icon in this product sits beside the word it stands for.
struct LucideIcon: View {
    let icon: Lucide
    var size: LucideSize = .md
    var label: String?

    var body: some View {
        let px = size.rawValue
        LucideShape(icon: icon)
            .stroke(style: StrokeStyle(lineWidth: 1.5 * px / 24, lineCap: .round, lineJoin: .round))
            .frame(width: px, height: px)
            .accessibilityHidden(label == nil)
            .accessibilityLabel(label ?? "")
    }
}

/// The icon's outline as a `Shape`, scaled from the 24 grid into whatever rect it is given.
struct LucideShape: Shape {
    let icon: Lucide

    func path(in rect: CGRect) -> Path {
        let scale = min(rect.width, rect.height) / 24
        let transform = CGAffineTransform(translationX: rect.minX, y: rect.minY)
            .scaledBy(x: scale, y: scale)
        return LucideMarkup.path(for: icon).applying(transform)
    }
}

/// SVG markup → `Path`, for the subset of SVG Lucide is drawn in: `path`, `circle`, `rect`,
/// `line`, `polyline`, `polygon`, `ellipse`, and path data using M L H V C S Q T A Z. Parsed once
/// per icon and cached — an icon is drawn on every frame a list scrolls.
enum LucideMarkup {
    private static var cache: [Lucide: Path] = [:]
    private static let lock = NSLock()

    static func path(for icon: Lucide) -> Path {
        lock.lock()
        defer { lock.unlock() }
        if let cached = cache[icon] { return cached }
        let built = build(icon.markup)
        cache[icon] = built
        return built
    }

    private static let element = try! NSRegularExpression(
        pattern: "<(path|circle|rect|line|polyline|polygon|ellipse)\\b([^>]*?)/?>")
    private static let attribute = try! NSRegularExpression(pattern: "([\\w-]+)=\"([^\"]*)\"")

    private static func build(_ markup: String) -> Path {
        var path = Path()
        let whole = NSRange(markup.startIndex..., in: markup)
        for match in element.matches(in: markup, range: whole) {
            let name = String(markup[Range(match.range(at: 1), in: markup)!])
            let attrs = String(markup[Range(match.range(at: 2), in: markup)!])
            var values: [String: String] = [:]
            for a in attribute.matches(in: attrs, range: NSRange(attrs.startIndex..., in: attrs)) {
                let key = String(attrs[Range(a.range(at: 1), in: attrs)!])
                values[key] = String(attrs[Range(a.range(at: 2), in: attrs)!])
            }
            func number(_ key: String, _ fallback: CGFloat = 0) -> CGFloat {
                values[key].flatMap { Double($0) }.map { CGFloat($0) } ?? fallback
            }
            switch name {
            case "path":
                if let d = values["d"] { PathData(d).append(to: &path) }
            case "circle":
                let r = number("r")
                path.addEllipse(in: CGRect(x: number("cx") - r, y: number("cy") - r,
                                           width: 2 * r, height: 2 * r))
            case "ellipse":
                let rx = number("rx"), ry = number("ry")
                path.addEllipse(in: CGRect(x: number("cx") - rx, y: number("cy") - ry,
                                           width: 2 * rx, height: 2 * ry))
            case "rect":
                let rect = CGRect(x: number("x"), y: number("y"),
                                  width: number("width"), height: number("height"))
                let rx = number("rx", number("ry"))
                let ry = number("ry", rx)
                if rx > 0 || ry > 0 {
                    path.addRoundedRect(in: rect, cornerSize: CGSize(width: rx, height: ry))
                } else {
                    path.addRect(rect)
                }
            case "line":
                path.move(to: CGPoint(x: number("x1"), y: number("y1")))
                path.addLine(to: CGPoint(x: number("x2"), y: number("y2")))
            case "polyline", "polygon":
                let points = PathData.numbers(in: values["points"] ?? "")
                var first = true
                for i in stride(from: 0, to: points.count - 1, by: 2) {
                    let point = CGPoint(x: points[i], y: points[i + 1])
                    if first { path.move(to: point); first = false } else { path.addLine(to: point) }
                }
                if name == "polygon" { path.closeSubpath() }
            default:
                break
            }
        }
        return path
    }
}

/// The `d` attribute of an SVG `<path>`, appended to a `Path`.
///
/// Arcs are the one command a `Path` has no primitive for; they are converted to cubic Béziers
/// through the endpoint-to-centre parameterisation in the SVG specification, a quarter turn per
/// segment. Relative forms and the implicit line after a move are handled; everything else in
/// the grammar (only ever numbers and letters) is left alone.
struct PathData {
    private let d: String

    init(_ d: String) { self.d = d }

    static func numbers(in text: String) -> [CGFloat] {
        var out: [CGFloat] = []
        var current = ""
        func flush() {
            if let v = Double(current) { out.append(CGFloat(v)) }
            current = ""
        }
        for ch in text {
            switch ch {
            case "0"..."9":
                current.append(ch)
            case ".":
                // A second point starts a new number: `7.54.54` is two.
                if current.contains(".") { flush() }
                current.append(ch)
            case "-", "+":
                // A sign starts a new number unless it follows an exponent.
                if !current.isEmpty, !current.hasSuffix("e"), !current.hasSuffix("E") { flush() }
                current.append(ch)
            case "e", "E":
                current.append(ch)
            default:
                flush()
            }
        }
        flush()
        return out
    }

    func append(to path: inout Path) {
        var tokens: [Token] = []
        var run = ""
        func flushRun() {
            if !run.isEmpty {
                tokens.append(contentsOf: Self.numbers(in: run).map(Token.number))
                run = ""
            }
        }
        for ch in d {
            if ch.isLetter, ch != "e", ch != "E" {
                flushRun()
                tokens.append(.command(ch))
            } else {
                run.append(ch)
            }
        }
        flushRun()

        var current = CGPoint.zero
        var start = CGPoint.zero
        var control: CGPoint? = nil   // the reflected control point for S / T
        var lastCommand: Character = "M"
        var i = 0

        func take() -> CGFloat {
            defer { i += 1 }
            if case let .number(v) = tokens[i] { return v }
            return 0
        }
        func hasNumbers(_ n: Int) -> Bool {
            guard i + n <= tokens.count else { return false }
            for k in 0..<n { if case .command = tokens[i + k] { return false } }
            return true
        }

        while i < tokens.count {
            var command: Character
            if case let .command(c) = tokens[i] {
                command = c
                i += 1
            } else {
                // Numbers after a command repeat it; after a move they draw lines.
                command = lastCommand
                if command == "M" { command = "L" } else if command == "m" { command = "l" }
            }
            let relative = command.isLowercase
            let upper = Character(command.uppercased())
            func point(_ x: CGFloat, _ y: CGFloat) -> CGPoint {
                relative ? CGPoint(x: current.x + x, y: current.y + y) : CGPoint(x: x, y: y)
            }

            switch upper {
            case "M":
                guard hasNumbers(2) else { i = tokens.count; break }
                current = point(take(), take())
                start = current
                path.move(to: current)
                control = nil
            case "L":
                guard hasNumbers(2) else { i = tokens.count; break }
                current = point(take(), take())
                path.addLine(to: current)
                control = nil
            case "H":
                guard hasNumbers(1) else { i = tokens.count; break }
                let x = take()
                current = CGPoint(x: relative ? current.x + x : x, y: current.y)
                path.addLine(to: current)
                control = nil
            case "V":
                guard hasNumbers(1) else { i = tokens.count; break }
                let y = take()
                current = CGPoint(x: current.x, y: relative ? current.y + y : y)
                path.addLine(to: current)
                control = nil
            case "C":
                guard hasNumbers(6) else { i = tokens.count; break }
                let c1 = point(take(), take())
                let c2 = point(take(), take())
                let end = point(take(), take())
                path.addCurve(to: end, control1: c1, control2: c2)
                control = c2
                current = end
            case "S":
                guard hasNumbers(4) else { i = tokens.count; break }
                let c1 = control.map { CGPoint(x: 2 * current.x - $0.x, y: 2 * current.y - $0.y) } ?? current
                let c2 = point(take(), take())
                let end = point(take(), take())
                path.addCurve(to: end, control1: c1, control2: c2)
                control = c2
                current = end
            case "Q":
                guard hasNumbers(4) else { i = tokens.count; break }
                let c = point(take(), take())
                let end = point(take(), take())
                path.addQuadCurve(to: end, control: c)
                control = c
                current = end
            case "T":
                guard hasNumbers(2) else { i = tokens.count; break }
                let c = control.map { CGPoint(x: 2 * current.x - $0.x, y: 2 * current.y - $0.y) } ?? current
                let end = point(take(), take())
                path.addQuadCurve(to: end, control: c)
                control = c
                current = end
            case "A":
                guard hasNumbers(7) else { i = tokens.count; break }
                let rx = take(), ry = take(), rotation = take()
                let largeArc = take() != 0, sweep = take() != 0
                let end = point(take(), take())
                Self.arc(from: current, to: end, rx: rx, ry: ry, rotation: rotation,
                         largeArc: largeArc, sweep: sweep, into: &path)
                current = end
                control = nil
            case "Z":
                path.closeSubpath()
                current = start
                control = nil
            default:
                i = tokens.count
            }
            lastCommand = command
        }
    }

    private enum Token {
        case command(Character)
        case number(CGFloat)
    }

    /// SVG arc → cubic Béziers (SVG 1.1 implementation notes, F.6.5 and F.6.6).
    private static func arc(from p1: CGPoint, to p2: CGPoint, rx: CGFloat, ry: CGFloat,
                            rotation: CGFloat, largeArc: Bool, sweep: Bool, into path: inout Path) {
        if p1 == p2 { return }
        var rx = abs(rx), ry = abs(ry)
        if rx == 0 || ry == 0 {
            path.addLine(to: p2)
            return
        }
        let phi = rotation * .pi / 180
        let cosPhi = cos(phi), sinPhi = sin(phi)
        let dx = (p1.x - p2.x) / 2, dy = (p1.y - p2.y) / 2
        let x1p = cosPhi * dx + sinPhi * dy
        let y1p = -sinPhi * dx + cosPhi * dy
        // Scale the radii up if the endpoints are too far apart for them.
        let lambda = (x1p * x1p) / (rx * rx) + (y1p * y1p) / (ry * ry)
        if lambda > 1 {
            rx *= sqrt(lambda)
            ry *= sqrt(lambda)
        }
        let num = rx * rx * ry * ry - rx * rx * y1p * y1p - ry * ry * x1p * x1p
        let den = rx * rx * y1p * y1p + ry * ry * x1p * x1p
        var coefficient = den == 0 ? 0 : sqrt(max(0, num / den))
        if largeArc == sweep { coefficient = -coefficient }
        let cxp = coefficient * (rx * y1p / ry)
        let cyp = coefficient * -(ry * x1p / rx)
        let cx = cosPhi * cxp - sinPhi * cyp + (p1.x + p2.x) / 2
        let cy = sinPhi * cxp + cosPhi * cyp + (p1.y + p2.y) / 2

        func angle(_ ux: CGFloat, _ uy: CGFloat, _ vx: CGFloat, _ vy: CGFloat) -> CGFloat {
            let dot = ux * vx + uy * vy
            let len = sqrt(ux * ux + uy * uy) * sqrt(vx * vx + vy * vy)
            var a = acos(max(-1, min(1, dot / len)))
            if ux * vy - uy * vx < 0 { a = -a }
            return a
        }
        let theta1 = angle(1, 0, (x1p - cxp) / rx, (y1p - cyp) / ry)
        var delta = angle((x1p - cxp) / rx, (y1p - cyp) / ry, (-x1p - cxp) / rx, (-y1p - cyp) / ry)
        if !sweep, delta > 0 { delta -= 2 * .pi }
        if sweep, delta < 0 { delta += 2 * .pi }

        // Split into segments of at most a quarter turn; each is one cubic.
        let segments = max(1, Int(ceil(abs(delta) / (.pi / 2) - 0.0001)))
        let step = delta / CGFloat(segments)
        var theta = theta1
        let t = 4 / 3 * tan(step / 4)
        for _ in 0..<segments {
            let cos1 = cos(theta), sin1 = sin(theta)
            let cos2 = cos(theta + step), sin2 = sin(theta + step)
            // Points on the unit circle, then the control handles, then back through the ellipse.
            func map(_ x: CGFloat, _ y: CGFloat) -> CGPoint {
                let ex = rx * x, ey = ry * y
                return CGPoint(x: cosPhi * ex - sinPhi * ey + cx, y: sinPhi * ex + cosPhi * ey + cy)
            }
            let c1 = map(cos1 - t * sin1, sin1 + t * cos1)
            let c2 = map(cos2 + t * sin2, sin2 - t * cos2)
            let end = map(cos2, sin2)
            path.addCurve(to: end, control1: c1, control2: c2)
            theta += step
        }
    }
}
