/**
 * Markdown helpers shared by every generated document.
 *
 * They exist so that document modules read as prose with holes in it, rather than as string
 * concatenation with prose trapped inside.
 */

/**
 * The column the generated prose is wrapped to, matching the hand-written prose it sits between.
 * A generated paragraph on one 400-character line is unreadable in the diff that is supposed to be
 * this document's review step.
 */
const WIDTH = 100;

function wrapLines(text: string, width: number): string[] {
  const lines: string[] = [];
  let line = "";
  for (const word of text.trim().split(/\s+/)) {
    const candidate = line ? `${line} ${word}` : word;
    // A word longer than the column — a URL — goes on its own line and overflows it, rather than
    // being broken into something that is no longer a link.
    if (line && candidate.length > width) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  }
  if (line) lines.push(line);
  return lines;
}

/** A paragraph wrapped to the document column, every line carrying `indent`. */
export function wrap(text: string, indent = ""): string {
  return wrapLines(text, WIDTH - indent.length)
    .map((l) => indent + l)
    .join("\n");
}

/** A list item whose continuation lines line up under its own text rather than under the marker. */
export function bullet(text: string, indent = ""): string {
  const first = `${indent}- `;
  const continuation = " ".repeat(first.length);
  return wrapLines(text, WIDTH - first.length)
    .map((l, i) => (i === 0 ? first + l : continuation + l))
    .join("\n");
}

/** Cell text that cannot break the table it is put in. */
export function cell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\s*\n\s*/g, " ");
}

/** A GitHub-flavoured table. Rows are printed in the order given — sort before calling. */
export function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.map(cell).join(" | ")} |`;
  const rule = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((r) => `| ${r.map(cell).join(" | ")} |`);
  return [head, rule, ...body].join("\n");
}

/**
 * Joins blocks with exactly one blank line between them, dropping empties.
 *
 * Callers build sections conditionally, and an omitted one must not leave a double blank line
 * behind — whitespace churn in the diff of a legal document costs a reviewer the thing the diff
 * was for.
 */
export function blocks(...parts: (string | null | undefined)[]): string {
  return parts
    .filter((p): p is string => Boolean(p?.trim()))
    // Leading blank lines go, leading *spaces* stay: a block nested inside a list item carries its
    // indentation on its first line, and trimming it would unnest the block.
    .map((p) => p.replace(/^\n+/, "").replace(/\s+$/, ""))
    .join("\n\n");
}

/** The header that tells a reader — and GitHub — that editing this file by hand is pointless. */
export function generatedBanner(command: string, sources: string[]): string {
  return `<!-- @generated by \`${command}\` from ${sources.join(", ")} — do not edit by hand. -->`;
}

/** Wraps `text` into a Markdown blockquote, preserving its paragraph breaks. */
export function quote(text: string): string {
  return text
    .trim()
    .split("\n")
    .map((line) => (line.trim() ? `> ${line.trim()}` : ">"))
    .join("\n");
}
