//! Turns `icons/*.svg` — the Lucide set `scripts/lucide.sh` fetches — into the `Lucide` enum
//! that `src/icon.rs` includes from `$OUT_DIR/lucide.rs`.
//!
//! Generated rather than hand-written so an icon is added by dropping its file in: the enum,
//! its `name()` and its markup all follow from the directory. Each SVG is kept verbatim on
//! disk (licence header included — the ISC notice has to travel with the paths) and only the
//! *inside* of the `<svg>` element is compiled in; the wrapper is drawn by the component, which
//! is where the size, the stroke width and the `aria` attributes are decided.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let dir = Path::new(&manifest).join("icons");
    let out = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("lucide.rs");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut icons: Vec<(String, String)> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .flatten()
        .filter_map(|entry| {
            let path = entry.path();
            let name = path.file_stem()?.to_str()?.to_string();
            (path.extension()?.to_str()? == "svg").then(|| {
                println!("cargo:rerun-if-changed={}", path.display());
                let svg = std::fs::read_to_string(&path)
                    .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
                (name, inner(&svg))
            })
        })
        .collect();
    icons.sort();
    assert!(
        !icons.is_empty(),
        "no icons in {} — run scripts/lucide.sh",
        dir.display()
    );

    let mut src = String::new();
    src.push_str(
        "/// One Lucide icon, by name. Generated by `build.rs` from `icons/*.svg`; add a name to\n\
         /// `icons/ICONS`, run `scripts/lucide.sh`, and the variant appears here.\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n\
         #[allow(missing_docs)]\n\
         pub enum Lucide {\n",
    );
    for (name, _) in &icons {
        let _ = writeln!(src, "    /// `{name}`\n    {},", variant(name));
    }
    src.push_str("}\n\nimpl Lucide {\n    /// Every icon in the set, in name order.\n    pub const ALL: &'static [Lucide] = &[\n");
    for (name, _) in &icons {
        let _ = writeln!(src, "        Lucide::{},", variant(name));
    }
    src.push_str("    ];\n\n    /// The icon's name on lucide.dev — `arrow-up-right`, `settings-2`.\n    #[must_use]\n    pub const fn name(self) -> &'static str {\n        match self {\n");
    for (name, _) in &icons {
        let _ = writeln!(src, "            Lucide::{} => {name:?},", variant(name));
    }
    src.push_str("        }\n    }\n\n    /// The icon by its lucide.dev name, if it is in the set.\n    #[must_use]\n    pub fn from_name(name: &str) -> Option<Lucide> {\n        match name {\n");
    for (name, _) in &icons {
        let _ = writeln!(
            src,
            "            {name:?} => Some(Lucide::{}),",
            variant(name)
        );
    }
    src.push_str("            _ => None,\n        }\n    }\n\n    /// The inside of the icon's `<svg>`: the paths, on a 24×24 grid, stroked in `currentColor`\n    /// by whatever element wraps them.\n    #[must_use]\n    pub const fn markup(self) -> &'static str {\n        match self {\n");
    for (name, markup) in &icons {
        let _ = writeln!(src, "            Lucide::{} => {markup:?},", variant(name));
    }
    src.push_str("        }\n    }\n}\n");

    std::fs::write(&out, src).expect("writing lucide.rs");
}

/// `arrow-up-right` → `ArrowUpRight`, `settings-2` → `Settings2`.
fn variant(name: &str) -> String {
    name.split('-')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => first.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// What sits between `<svg …>` and `</svg>`, with the licence comment dropped and the
/// whitespace collapsed — the paths are all a component needs, and every byte here is shipped
/// in the wasm bundle once per icon.
fn inner(svg: &str) -> String {
    let start = svg.find("<svg").expect("an <svg> element");
    let body_start = start + svg[start..].find('>').expect("the end of the <svg> tag") + 1;
    let body_end = svg.rfind("</svg>").expect("a closing </svg>");
    svg[body_start..body_end]
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .replace("> <", "><")
}
