//! Turn a scanned crate into the markdown of its `structs.gen.md`.
//!
//! The page is deliberately boring: an index, then one section per source file, then one fenced
//! declaration per type. Nothing in it depends on the clock, the machine or the order of a
//! directory listing, so re-running the tool on an unchanged tree produces a byte-identical file
//! and an empty `git diff`.

use std::fmt::Write as _;

use crate::scan::{Body, CrateTypes, Decl, Field, Kind, Variant};

/// The line every generated page opens with — a marker for humans, reviewers and `.gitattributes`.
const BANNER: &str = "<!-- @generated by `cargo run -p adi-structs` — do not edit by hand. -->";

pub(crate) fn page(krate: &CrateTypes) -> String {
    let mut out = String::with_capacity(64 * 1024);
    let _ = writeln!(out, "{BANNER}\n");
    let _ = writeln!(out, "# `{}` — types\n", krate.name);
    if let Some(desc) = &krate.description {
        let _ = writeln!(out, "> {desc}\n");
    }

    let (structs, enums, aliases) = counts(krate);
    if structs + enums + aliases == 0 {
        let _ = writeln!(out, "This crate declares no structs, enums or type aliases.");
        return out;
    }
    let _ = writeln!(
        out,
        "{} across {}.\n",
        join_counts(structs, enums, aliases),
        plural(krate.files.len(), "file", "files")
    );

    let _ = writeln!(out, "## Index\n");
    for file in &krate.files {
        let names = file
            .decls
            .iter()
            .map(|d| format!("`{}`", d.qualified_name()))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out, "- [`{}`](#{}) — {names}", file.path, anchor(&file.path));
    }

    for file in &krate.files {
        let _ = writeln!(out, "\n---\n\n## `{}`\n", file.path);
        for decl in &file.decls {
            write_decl(&mut out, decl);
        }
    }
    squeeze_blank_lines(&out)
}

/// Sections and declarations each end with their own blank line, which stacks up where they meet.
/// One blank line is all markdown ever needs, so flatten any run of them down to one.
fn squeeze_blank_lines(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut blanks = 0;
    for line in s.lines() {
        if line.is_empty() {
            blanks += 1;
            if blanks > 1 {
                continue;
            }
        } else {
            blanks = 0;
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

fn write_decl(out: &mut String, decl: &Decl) {
    let _ = writeln!(
        out,
        "### {} `{}`\n",
        decl.kind.keyword(),
        decl.qualified_name()
    );
    if !decl.doc.is_empty() {
        let _ = writeln!(out, "{}\n", decl.doc);
    }
    let _ = writeln!(out, "```rust");
    for attr in &decl.attrs {
        let _ = writeln!(out, "{attr}");
    }
    let head = format!(
        "{}{}{} {}{}",
        decl.vis,
        if decl.vis.is_empty() { "" } else { " " },
        decl.kind.keyword(),
        decl.name,
        decl.generics,
    );
    match &decl.body {
        Body::Named(fields) => {
            let _ = writeln!(out, "{head} {{");
            write_fields(out, fields, 1, true);
            let _ = writeln!(out, "}}");
        }
        // A newtype is a one-liner in the source and stays one here — unless a field carries
        // attributes, which need a line of their own.
        Body::Tuple(fields) if fields.iter().all(|f| f.attrs.is_empty()) => {
            let inner = fields
                .iter()
                .map(|f| {
                    if f.vis.is_empty() {
                        f.ty.clone()
                    } else {
                        format!("{} {}", f.vis, f.ty)
                    }
                })
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "{head}({inner});");
        }
        Body::Tuple(fields) => {
            let _ = writeln!(out, "{head}(");
            write_fields(out, fields, 1, false);
            let _ = writeln!(out, ");");
        }
        Body::Unit => {
            let _ = writeln!(out, "{head};");
        }
        Body::Variants(variants) => {
            let _ = writeln!(out, "{head} {{");
            for variant in variants {
                write_variant(out, variant);
            }
            let _ = writeln!(out, "}}");
        }
        Body::Alias(ty) => {
            let _ = writeln!(out, "{head} = {ty};");
        }
    }
    let _ = writeln!(out, "```\n");
}

fn write_fields(out: &mut String, fields: &[Field], depth: usize, named: bool) {
    let pad = "    ".repeat(depth);
    for field in fields {
        for attr in &field.attrs {
            let _ = writeln!(out, "{pad}{attr}");
        }
        let vis = if field.vis.is_empty() {
            String::new()
        } else {
            format!("{} ", field.vis)
        };
        if named {
            let _ = writeln!(out, "{pad}{vis}{}: {},", field.name, field.ty);
        } else {
            let _ = writeln!(out, "{pad}{vis}{},", field.ty);
        }
    }
}

fn write_variant(out: &mut String, variant: &Variant) {
    for attr in &variant.attrs {
        let _ = writeln!(out, "    {attr}");
    }
    match &variant.body {
        Body::Named(fields) => {
            let _ = writeln!(out, "    {} {{", variant.name);
            write_fields(out, fields, 2, true);
            let _ = writeln!(out, "    }},");
        }
        Body::Tuple(fields) => {
            let inner = fields
                .iter()
                .map(|f| f.ty.clone())
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(out, "    {}({inner}),", variant.name);
        }
        _ => {
            let _ = writeln!(out, "    {}{},", variant.name, variant.discriminant);
        }
    }
}

fn counts(krate: &CrateTypes) -> (usize, usize, usize) {
    let mut counts = (0, 0, 0);
    for decl in krate.files.iter().flat_map(|f| &f.decls) {
        match decl.kind {
            Kind::Struct => counts.0 += 1,
            Kind::Enum => counts.1 += 1,
            Kind::Alias => counts.2 += 1,
        }
    }
    counts
}

fn join_counts(structs: usize, enums: usize, aliases: usize) -> String {
    [
        (structs, "struct", "structs"),
        (enums, "enum", "enums"),
        (aliases, "type alias", "type aliases"),
    ]
    .into_iter()
    .filter(|(n, _, _)| *n > 0)
    .map(|(n, one, many)| plural(n, one, many))
    .collect::<Vec<_>>()
    .join(" · ")
}

fn plural(n: usize, one: &str, many: &str) -> String {
    format!("{n} {}", if n == 1 { one } else { many })
}

/// GitHub's heading anchor for one of this page's file headings: lowercased, punctuation dropped.
fn anchor(path: &str) -> String {
    path.chars()
        .filter_map(|c| match c {
            'a'..='z' | '0'..='9' | '-' | '_' => Some(c),
            'A'..='Z' => Some(c.to_ascii_lowercase()),
            ' ' => Some('-'),
            _ => None,
        })
        .collect()
}
