// Glyphs are generated by scripts/lucide.sh from crates/adi-ui/icons/*.svg.

import { AdiElement, define } from "./base.ts";
import { ICONS } from "./icons.gen.ts";

const SIZES = [14, 16, 20, 24];

// Warn once per unknown name, even when it appears in multiple rows.
const warned = new Set<string>();

function snap(value: string | null): number {
  const size = Number(value);
  if (!size) return 16;
  if (SIZES.includes(size)) return size;
  return SIZES.reduce((best, s) => (Math.abs(s - size) < Math.abs(best - size) ? s : best));
}

class AdiIcon extends AdiElement {
  static observedAttributes = ["name", "size", "label"];

  override template() {
    return `<svg part="svg" viewBox="0 0 24 24"></svg>`;
  }

  override update() {
    const svg = this.must<SVGSVGElement>("svg");
    const name = this.attr("name");
    const body = ICONS[name];
    if (body === undefined && !warned.has(name)) {
      warned.add(name);
      console.warn(
        `adi-icon: no Lucide icon named "${name}". Add it to crates/adi-ui/icons/ICONS and run scripts/lucide.sh.`,
      );
    }
    svg.innerHTML = body ?? "";

    const size = snap(this.getAttribute("size"));
    svg.setAttribute("width", String(size));
    svg.setAttribute("height", String(size));

    const label = this.getAttribute("label");
    if (label) {
      this.setAttribute("role", "img");
      this.setAttribute("aria-label", label);
      this.removeAttribute("aria-hidden");
    } else {
      this.setAttribute("aria-hidden", "true");
      this.removeAttribute("role");
      this.removeAttribute("aria-label");
    }
  }
}

define("adi-icon", AdiIcon);

/** Every icon name in the set, sorted — what the gallery lists and what `name` accepts. */
export const ICON_NAMES = Object.keys(ICONS);

export { AdiIcon };

declare global {
  interface HTMLElementTagNameMap {
    "adi-icon": AdiIcon;
  }
}
