#!/usr/bin/env bash
# The three typefaces (design/DESIGN.md §4), self-hosted: fetched once from Google Fonts as
# per-script woff2 subsets into crates/adi-ui/fonts/, with the @font-face rules written to
# crates/adi-ui/fonts/fonts.css. Self-hosted rather than linked so the control panel makes no
# third-party request and the installed app keeps its type offline.
#
#   scripts/fonts.sh      # refetch everything and rewrite fonts.css
#
# Variable fonts, one file per script: Geist and Geist Mono cover latin, latin-ext, cyrillic and
# cyrillic-ext (transcripts are read in Russian as often as English); Geist Mono also takes
# symbols2, the box-drawing range terminal output uses. Bricolage Grotesque is for landing
# headlines only, so it carries latin and latin-ext.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/crates/adi-ui/fonts"
UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36"

# family-as-css-name | Google Fonts query | file stem | weight range | subsets (space-separated)
FAMILIES=(
  "Geist|Geist:wght@100..900|geist|100 900|latin latin-ext cyrillic cyrillic-ext"
  "Geist Mono|Geist+Mono:wght@100..900|geist-mono|100 900|latin latin-ext cyrillic cyrillic-ext symbols2"
  "Bricolage Grotesque|Bricolage+Grotesque:opsz,wght@12..96,200..800|bricolage|200 800|latin latin-ext"
)

OUT="$DIR/fonts.css"
{
  echo "/* Generated by scripts/fonts.sh — do not edit. The files beside this sheet are the three"
  echo "   faces in design/DESIGN.md §4, one woff2 per script, served from /fonts/ at the dist root. */"
} > "$OUT"

for spec in "${FAMILIES[@]}"; do
  IFS='|' read -r family query stem range subsets <<< "$spec"
  css=$(curl -sS -A "$UA" "https://fonts.googleapis.com/css2?family=${query}&display=swap")
  for subset in $subsets; do
    # The block for one subset: the comment names it, then src and unicode-range follow.
    block=$(printf '%s\n' "$css" | awk -v s="/* $subset */" '$0==s{f=1;next} f&&/^}/{exit} f')
    url=$(printf '%s\n' "$block" | sed -n 's/.*url(\([^)]*\)).*/\1/p' | head -1)
    ranges=$(printf '%s\n' "$block" | sed -n 's/.*unicode-range: *\(.*\);/\1/p' | head -1)
    if [ -z "$url" ]; then echo "fonts: no $subset subset for $family" >&2; exit 1; fi
    file="$stem-$subset.woff2"
    curl -sS -o "$DIR/$file" "$url"
    printf '\n@font-face {\n  font-family: "%s";\n  src: url("/fonts/%s") format("woff2");\n  font-weight: %s;\n  font-style: normal;\n  font-display: swap;\n  unicode-range: %s;\n}\n' \
      "$family" "$file" "$range" "$ranges" >> "$OUT"
    echo "  $family / $subset  ← $file ($(stat -f %z "$DIR/$file") bytes)"
  done
done
