#!/usr/bin/env bash
# Fetch pinned Lucide SVGs and generate the TypeScript icon map.
# Usage: scripts/lucide.sh [--all | add <name>…]
set -euo pipefail

VERSION="1.39.0"
CDN="https://cdn.jsdelivr.net/npm/lucide-static@${VERSION}/icons"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/crates/adi-ui/icons"
LIST="$DIR/ICONS"
ELEMENTS_TS="$ROOT/design/elements/icons.gen.ts"

names() { grep -v '^\s*#' "$LIST" | sed '/^\s*$/d'; }

fetch() {
  local name="$1" out="$DIR/$1.svg" code
  code=$(curl -sS -o "$out.tmp" -w '%{http_code}' "$CDN/$name.svg")
  if [ "$code" != "200" ]; then
    rm -f "$out.tmp"
    echo "lucide: no icon named '$name' in lucide-static ${VERSION} (HTTP $code)" >&2
    return 1
  fi
  mv "$out.tmp" "$out"
  echo "  $name"
}

# Strip the SVG wrapper; components provide size, stroke width, and colour.
inner() {
  awk '/^<\/svg>/ { f = 0 } f { sub(/^[ \t]+/, ""); printf "%s ", $0 } /^>$/ { f = 1 }' "$1" \
    | sed 's/ *$//'
}

# Lucide markup uses double-quoted attributes, so single-quoted values are safe.
generate_ts() {
  mkdir -p "$(dirname "$ELEMENTS_TS")"
  {
    echo "// Lucide icons, as markup the custom elements can draw. GENERATED by"
    echo "// scripts/lucide.sh from crates/adi-ui/icons/*.svg — do not edit; add a name to"
    echo "// crates/adi-ui/icons/ICONS and re-run the script."
    echo "//"
    echo "// @license lucide-static v${VERSION} - ISC (crates/adi-ui/icons/LICENSE)"
    echo ""
    echo "/** Every icon in the set, by its lucide name: the children of its \`<svg>\`. */"
    echo "export const ICONS: Readonly<Record<string, string>> = {"
    for n in $(names); do
      [ -f "$DIR/$n.svg" ] || continue
      printf "  %s: '%s',\n" "\"$n\"" "$(inner "$DIR/$n.svg")"
    done
    echo "};"
  } > "$ELEMENTS_TS.tmp"
  mv "$ELEMENTS_TS.tmp" "$ELEMENTS_TS"
  echo "  → $(basename "$ELEMENTS_TS") ($(grep -c '^  "' "$ELEMENTS_TS") icons)"
}

case "${1:-}" in
  add)
    shift
    for n in "$@"; do
      grep -qx "$n" "$LIST" || echo "$n" >> "$LIST"
    done
    { grep '^\s*#' "$LIST"; names | sort -u; } > "$LIST.tmp" && mv "$LIST.tmp" "$LIST"
    for n in "$@"; do fetch "$n"; done
    ;;
  --all)
    for n in $(names); do fetch "$n"; done
    ;;
  *)
    for n in $(names); do [ -f "$DIR/$n.svg" ] || fetch "$n"; done
    ;;
esac

generate_ts
