#!/usr/bin/env bash
# The Lucide icons the UI uses, fetched into crates/adi-ui/icons/ at one pinned release.
#
#   scripts/lucide.sh              # fetch every name in crates/adi-ui/icons/ICONS that is missing
#   scripts/lucide.sh --all        # refetch everything (after bumping VERSION)
#   scripts/lucide.sh add <name>…  # append names to ICONS, sorted, and fetch them
#
# The SVGs land verbatim, licence header included; `crates/adi-ui/build.rs` reads the directory
# and generates the `adi_ui::Lucide` enum from it, so adding an icon is: add the name here, run
# this, build. Names are checked against lucide.dev — a typo is a 404, never a silent blank.
#
# Two consumers, one directory. The Rust side reads it at build time; the custom elements in
# `design/elements` have no build step at all, so their copy is written out here as
# `icons.gen.js` on every run — which is why this script regenerates it even when nothing was
# fetched. One set of glyphs, whichever language draws them.
set -euo pipefail

VERSION="1.39.0"
CDN="https://cdn.jsdelivr.net/npm/lucide-static@${VERSION}/icons"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/crates/adi-ui/icons"
LIST="$DIR/ICONS"
ELEMENTS_JS="$ROOT/design/elements/icons.gen.js"

names() { grep -v '^\s*#' "$LIST" | sed '/^\s*$/d'; }

fetch() {
  local name="$1" out="$DIR/$1.svg" code
  code=$(curl -sS -o "$out.tmp" -w '%{http_code}' "$CDN/$name.svg")
  if [ "$code" != "200" ]; then
    rm -f "$out.tmp"
    echo "lucide: no icon named '$name' in lucide-static ${VERSION} (HTTP $code)" >&2
    return 1
  fi
  mv "$out.tmp" "$out"
  echo "  $name"
}

# The children of one `<svg>`, on a single line. Everything between the line that closes the
# opening tag (lucide-static writes it as a bare `>`) and `</svg>` — so the wrapper's own size,
# stroke width and colour are left to whichever component draws it, exactly as the Rust side
# does in crates/adi-ui/build.rs.
inner() {
  awk '/^<\/svg>/ { f = 0 } f { sub(/^[ \t]+/, ""); printf "%s ", $0 } /^>$/ { f = 1 }' "$1" \
    | sed 's/ *$//'
}

# The whole directory as one ES module. Single-quoted values are safe: lucide's markup quotes
# every attribute with `"`, and a path is digits and letters.
generate_js() {
  mkdir -p "$(dirname "$ELEMENTS_JS")"
  {
    echo "// Lucide icons, as markup the custom elements can draw. GENERATED by"
    echo "// scripts/lucide.sh from crates/adi-ui/icons/*.svg — do not edit; add a name to"
    echo "// crates/adi-ui/icons/ICONS and re-run the script."
    echo "//"
    echo "// @license lucide-static v${VERSION} - ISC (crates/adi-ui/icons/LICENSE)"
    echo ""
    echo "/** Every icon in the set, by its lucide name: the children of its \`<svg>\`. */"
    echo "export const ICONS = {"
    for n in $(names); do
      [ -f "$DIR/$n.svg" ] || continue
      printf "  %s: '%s',\n" "\"$n\"" "$(inner "$DIR/$n.svg")"
    done
    echo "};"
  } > "$ELEMENTS_JS.tmp"
  mv "$ELEMENTS_JS.tmp" "$ELEMENTS_JS"
  echo "  → $(basename "$ELEMENTS_JS") ($(grep -c '^  "' "$ELEMENTS_JS") icons)"
}

case "${1:-}" in
  add)
    shift
    for n in "$@"; do
      grep -qx "$n" "$LIST" || echo "$n" >> "$LIST"
    done
    { grep '^\s*#' "$LIST"; names | sort -u; } > "$LIST.tmp" && mv "$LIST.tmp" "$LIST"
    for n in "$@"; do fetch "$n"; done
    ;;
  --all)
    for n in $(names); do fetch "$n"; done
    ;;
  *)
    for n in $(names); do [ -f "$DIR/$n.svg" ] || fetch "$n"; done
    ;;
esac

generate_js
