//! adi-tools — register, edit, and run *tools*: small CLIs an agent invokes. A pure library
//! (no CLI, no daemon) over the shared [`adi_config`] store, mirroring [`adi_projects`].
//!
//! Each tool is a directory under `~/.adi/mono/tools/<id>/` whose `config.toml` is a metadata
//! [`Manifest`]. A tool is either:
//!
//! * **owned** — its script lives in the store at `tools/<id>/script.<ext>`, created and edited
//!   through here; or
//! * **linked** — [`Manifest::linked_path`] points at an existing file on disk, which the store
//!   reads and (optionally) writes through to but never copies or deletes.
//!
//! Every active tool is also exposed as a `tools/.bin/<name>` shim — a tiny `sh` script that
//! `exec`s `adi-mono tools run <id> "$@"` — so an agent with that `.bin` on its `PATH` runs a
//! tool by name. The shims are regenerated from the manifests on every mutation.
//!
//! A tool's id is minted from its name ([`adi_config::mint`]), so `confirm-sync` is both what it
//! is called and where it lives. Ids minted before that rule are UUIDs and stay exactly as they
//! are; [`rename`](Tools::rename) is how one becomes a name, and the UUID it had keeps resolving
//! through the registry's alias index forever after — 75 agent definitions cite tool ids verbatim
//! in their `bin_tools`, and none of them may stop working because a tool was given a better name.
//!
//! ```
//! # let tmp = std::env::temp_dir().join(format!("adi-tools-doctest-{}", std::process::id()));
//! # let _ = std::fs::remove_dir_all(&tmp);
//! use adi_tools::Tools;
//!
//! # let store = Tools::with_config(adi_config::Config::with_root(&tmp));
//! // In real code: let store = Tools::open();
//! let tool = store.create_file("greet", None, "sh", None, Some("echo hi\n".into()))?;
//! assert_eq!(tool.manifest.name, "greet");
//! assert!(!tool.is_linked());
//! assert_eq!(store.read_script(&tool.id)?.trim(), "echo hi");
//!
//! store.archive(&tool.id)?;
//! assert!(store.get(&tool.id)?.unwrap().is_archived());
//! # std::fs::remove_dir_all(&tmp).ok();
//! # Ok::<(), adi_tools::Error>(())
//! ```

mod error;
mod help;
mod run;
mod system;
mod tool;

use adi_config::{Aliases, clean, optional};
use std::path::{Path, PathBuf};

use adi_config::{Config, ConfigFile, Module, now_unix};

pub use error::{Error, Result};
pub use help::ToolHelp;
pub use run::RunOutput;
pub use system::{SYS_FACTS, SYS_KNOWLEDGE, SYS_KNOWLEDGE_ROOT};
pub use tool::{
    Manifest, RUNTIME_SH, RUNTIME_TS, Tool, normalize_runtime, runtime_ext, runtime_from_path,
    validate_runtime,
};

use tool::validate_id;

/// The store module tools live under, the manifest file within each tool dir, the owned-script
/// stem, and the shim directory agents put on their `PATH`.
const TOOLS_MODULE: &str = "tools";
const MANIFEST_FILE: &str = "config.toml";
const SCRIPT_STEM: &str = "script";
const BIN_DIR: &str = ".bin";
/// The parent of the per-agent bin dirs (`tools/.agent-bin/<agent>`). Dot-prefixed so
/// [`Tools::list`] skips it, and separate from [`BIN_DIR`] so regenerating one never wipes the other.
const AGENT_BIN_DIR: &str = ".agent-bin";
/// The word a tool's id falls back to when its name has nothing sluggable in it.
const ID_FALLBACK: &str = "tool";

/// The tools registry: lists, reads, edits, and runs the per-tool manifests + scripts under the
/// `tools` module dir. Cheap to clone; all state is on disk.
#[derive(Debug, Clone)]
pub struct Tools {
    config: Config,
}

impl Default for Tools {
    fn default() -> Self {
        Self::open()
    }
}

impl Tools {
    /// Open the registry backed by the standard store (`~/.adi/mono`, honoring `$ADI_DIR`).
    #[must_use]
    pub fn open() -> Self {
        Self {
            config: Config::open(),
        }
    }

    /// Open the registry backed by a caller-supplied [`Config`] — for tests or alternate installs.
    #[must_use]
    pub fn with_config(config: Config) -> Self {
        Self { config }
    }

    /// The store this registry reads from.
    #[must_use]
    pub fn config(&self) -> &Config {
        &self.config
    }

    /// The `tools` directory: `~/.adi/mono/tools`.
    #[must_use]
    pub fn dir(&self) -> PathBuf {
        self.config.module(TOOLS_MODULE).dir().to_path_buf()
    }

    /// The shim directory agents add to their `PATH`: `~/.adi/mono/tools/.bin`. Holds one
    /// `sh` shim per active tool (regenerated by [`sync_bin`](Self::sync_bin)).
    #[must_use]
    pub fn bin_dir(&self) -> PathBuf {
        self.dir().join(BIN_DIR)
    }

    /// A tool's own directory: `tools/<id>`. Returns the path even if it doesn't exist yet.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id — the security boundary before the id is joined onto
    /// the store path.
    pub fn tool_dir(&self, id: &str) -> Result<PathBuf> {
        Ok(self.dir().join(self.resolve(id)?))
    }

    /// The manifest file handle for `id`, at `tools/<id>/config.toml` (touches no disk).
    fn manifest_file(&self, id: &str) -> ConfigFile<Manifest> {
        self.module().file(&format!("{id}/{MANIFEST_FILE}"))
    }

    /// The `tools` module handle — the directory the manifests and the alias index share.
    fn module(&self) -> Module {
        self.config.module(TOOLS_MODULE)
    }

    /// The ids tools used to have, each pointing at the id it has now. See [`Aliases`].
    ///
    /// # Errors
    /// [`Error::Config`] if the index exists but can't be read or parsed.
    pub fn aliases(&self) -> Result<Aliases> {
        Ok(Aliases::load(&self.module())?)
    }

    /// The id `id` actually names: itself when a tool is registered under it, else what the alias
    /// index says the tool was renamed to, else `id` unchanged (so "no such tool" is reported
    /// against the id the caller typed rather than something it was silently rewritten to).
    ///
    /// This is the one place a legacy UUID becomes a current id, and every read and mutation path
    /// goes through it — which is what makes an old `bin_tools` entry, a stale shim, or a UUID out
    /// of somebody's shell history keep working after a rename.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id, or [`Error::Config`] on an unreadable alias index.
    pub fn resolve(&self, id: &str) -> Result<String> {
        validate_id(id)?;
        if self.manifest_file(id).exists() {
            return Ok(id.to_string());
        }
        Ok(self.aliases()?.target(id).unwrap_or(id).to_string())
    }

    /// Whether anything occupies `id`: a tool's directory (registered or half-made by hand), or an
    /// id some tool was renamed away from. Both count, because minting an id that still resolves
    /// elsewhere would silently re-point every reference that names it.
    fn is_taken(&self, id: &str, aliases: &Aliases) -> bool {
        self.dir().join(id).exists() || aliases.is_alias(id)
    }

    /// Mint the id for a new tool called `name` — a slug of the name, uniquified against
    /// everything already taken. See [`adi_config::mint`].
    fn mint_id(&self, name: &str) -> Result<String> {
        let aliases = self.aliases()?;
        Ok(adi_config::mint(name, ID_FALLBACK, |candidate| {
            self.is_taken(candidate, &aliases)
        }))
    }

    /// Where a tool's script lives: the linked file for a linked tool, else the owned
    /// `tools/<id>/script.<ext>` in the store. Returns the path even if it doesn't exist.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id, [`Error::NotFound`] when the tool isn't registered.
    pub fn script_path(&self, id: &str) -> Result<PathBuf> {
        let tool = self.require(id)?;
        Ok(self.script_path_of(&tool))
    }

    /// The script path of an already-loaded tool (no disk read) — see [`script_path`](Self::script_path).
    fn script_path_of(&self, tool: &Tool) -> PathBuf {
        match &tool.manifest.linked_path {
            Some(path) => PathBuf::from(path),
            None => self.dir().join(&tool.id).join(format!(
                "{SCRIPT_STEM}.{}",
                runtime_ext(&tool.manifest.runtime)
            )),
        }
    }

    /// Every registered tool, sorted by id. A tool dir without a `config.toml` isn't registered
    /// yet and is skipped; a missing `tools/` dir yields an empty list.
    ///
    /// # Errors
    /// [`Error::Io`] on a directory read failure, or [`Error::Config`] if a manifest is invalid TOML.
    pub fn list(&self) -> Result<Vec<Tool>> {
        let Some(entries) = optional(std::fs::read_dir(self.dir()))? else {
            return Ok(Vec::new());
        };

        let mut tools = Vec::new();
        for entry in entries {
            let entry = entry?;
            if !entry.file_type()?.is_dir() {
                continue;
            }
            let Ok(id) = entry.file_name().into_string() else {
                continue;
            };
            // The `.bin` shim dir (and any other dotfile) is not a tool.
            if id.starts_with('.') || validate_id(&id).is_err() {
                continue;
            }
            let file = self.manifest_file(&id);
            if !file.exists() {
                continue;
            }
            tools.push(Tool {
                id,
                manifest: file.load()?,
            });
        }
        tools.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(tools)
    }

    /// The tool with this id, or `None` if it isn't registered. `id` may be an id the tool no
    /// longer has (see [`resolve`](Self::resolve)); the returned [`Tool`] always carries the
    /// current one.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id, or [`Error::Config`] if the manifest is invalid TOML.
    pub fn get(&self, id: &str) -> Result<Option<Tool>> {
        let id = self.resolve(id)?;
        let file = self.manifest_file(&id);
        if !file.exists() {
            return Ok(None);
        }
        Ok(Some(Tool {
            id,
            manifest: file.load()?,
        }))
    }

    /// Register a new **owned** tool under an id minted from its name: writes its `config.toml`
    /// and an executable script (from `content`, or a runtime starter when omitted), then
    /// regenerates the `.bin` shims. A blank `name` falls back to the minted id.
    ///
    /// # Errors
    /// [`Error::InvalidRuntime`] for an unknown runtime, or [`Error::Config`]/[`Error::Io`] on a
    /// write failure.
    pub fn create_file(
        &self,
        name: &str,
        description: Option<String>,
        runtime: &str,
        project: Option<String>,
        content: Option<String>,
    ) -> Result<Tool> {
        let runtime = validate_runtime(runtime)?;
        let name = clean(Some(name.to_string()));
        let id = self.mint_id(name.as_deref().unwrap_or_default())?;
        let manifest = Manifest {
            name: name.clone().unwrap_or_else(|| id.clone()),
            description: clean(description),
            runtime: runtime.to_string(),
            linked_path: None,
            project: clean(project),
            system: false,
            created_at: now_unix(),
            archived_at: None,
        };
        let tool = Tool {
            id: id.clone(),
            manifest,
        };
        self.manifest_file(&id).save(&tool.manifest)?;
        let body = content.unwrap_or_else(|| starter(runtime, tool.display_name()));
        write_file(&self.script_path_of(&tool), &body)?;
        self.sync_bin()?;
        Ok(tool)
    }

    /// Register a new **linked** tool that points at an existing file `path` on disk under an id
    /// minted from its name: writes only a manifest (the file is never copied), then regenerates
    /// the `.bin` shims. `name` defaults to the file's stem, `runtime` is inferred from the
    /// extension when blank.
    ///
    /// # Errors
    /// [`Error::LinkedMissing`] when `path` doesn't exist, [`Error::InvalidRuntime`] for an
    /// explicit unknown runtime, or [`Error::Config`]/[`Error::Io`] on a write failure.
    pub fn link(
        &self,
        path: &str,
        name: Option<String>,
        runtime: Option<String>,
        description: Option<String>,
        project: Option<String>,
    ) -> Result<Tool> {
        let raw = PathBuf::from(path.trim());
        if !raw.exists() {
            return Err(Error::LinkedMissing(raw.display().to_string()));
        }
        // Store an absolute path so the shim/run resolve it regardless of the caller's cwd.
        let abs = std::fs::canonicalize(&raw).unwrap_or(raw);
        let runtime = match runtime.as_deref().map(str::trim).filter(|r| !r.is_empty()) {
            Some(r) => validate_runtime(r)?.to_string(),
            None => runtime_from_path(&abs.to_string_lossy()).to_string(),
        };
        let name = clean(name).unwrap_or_else(|| {
            abs.file_stem()
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_else(|| "tool".to_string())
        });

        let id = self.mint_id(&name)?;
        let manifest = Manifest {
            name,
            description: clean(description),
            runtime,
            linked_path: Some(abs.display().to_string()),
            project: clean(project),
            system: false,
            created_at: now_unix(),
            archived_at: None,
        };
        self.manifest_file(&id).save(&manifest)?;
        self.sync_bin()?;
        Ok(Tool { id, manifest })
    }

    /// The tool's script text — the owned `script.<ext>`, or the linked file's contents.
    ///
    /// # Errors
    /// [`Error::NotFound`] when unregistered, [`Error::LinkedMissing`] when a linked file is gone,
    /// or [`Error::Io`] on a read failure.
    pub fn read_script(&self, id: &str) -> Result<String> {
        let path = self.script_path(id)?;
        match std::fs::read_to_string(&path) {
            Ok(text) => Ok(text),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                Err(Error::LinkedMissing(path.display().to_string()))
            }
            Err(e) => Err(Error::Io(e)),
        }
    }

    /// Overwrite the tool's script — the owned `script.<ext>` in the store, or (for a linked tool)
    /// the linked file itself, since the user linked it to edit it here.
    ///
    /// # Errors
    /// [`Error::NotFound`] when unregistered, or [`Error::Io`] on a write failure.
    pub fn write_script(&self, id: &str, content: &str) -> Result<()> {
        let path = self.script_path(id)?;
        write_file(&path, content)
    }

    /// Archive a tool (soft delete), stamping `archived_at` and dropping its `.bin` shim so it can
    /// no longer be run by name. Idempotent: re-archiving keeps the original timestamp.
    ///
    /// # Errors
    /// [`Error::NotFound`] if unregistered, plus the usual id/config/io errors.
    pub fn archive(&self, id: &str) -> Result<Tool> {
        let mut tool = self.require(id)?;
        if tool.manifest.archived_at.is_none() {
            tool.manifest.archived_at = Some(now_unix());
            // `tool.id`, not `id`: the caller may have named the tool by an id it no longer has,
            // and writing the manifest back under that one would create a second, half-made tool.
            self.manifest_file(&tool.id).save(&tool.manifest)?;
            self.sync_bin()?;
        }
        Ok(tool)
    }

    /// Restore an archived tool, clearing `archived_at` and re-creating its `.bin` shim.
    /// Idempotent for an active tool.
    ///
    /// # Errors
    /// [`Error::NotFound`] if unregistered, plus the usual id/config/io errors.
    pub fn unarchive(&self, id: &str) -> Result<Tool> {
        let mut tool = self.require(id)?;
        if tool.manifest.archived_at.is_some() {
            tool.manifest.archived_at = None;
            self.manifest_file(&tool.id).save(&tool.manifest)?;
            self.sync_bin()?;
        }
        Ok(tool)
    }

    /// Permanently delete a tool's directory (its manifest and, for an owned tool, its script),
    /// then regenerate the `.bin` shims. A **linked** tool's target file is never touched — only
    /// the store's manifest dir is removed. A built-in **system** tool is protected: it cannot be
    /// hard-deleted (archive it to disable it instead). Returns `false` if the tool wasn't there.
    ///
    /// Every id the tool answered to goes with it: an alias to a deleted tool would hold that id
    /// reserved against a future mint for nobody's benefit, since the thing it pointed at is gone.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id, [`Error::SystemProtected`] for a system tool, or
    /// [`Error::Io`] on a removal failure.
    pub fn remove(&self, id: &str) -> Result<bool> {
        let id = self.resolve(id)?;
        if self.get(&id)?.is_some_and(|t| t.is_system()) {
            return Err(Error::SystemProtected(id));
        }
        let dir = self.dir().join(&id);
        let removed = optional(std::fs::remove_dir_all(&dir))?.is_some();
        if removed {
            Aliases::forget(&self.module(), &id)?;
            self.sync_bin()?;
        }
        Ok(removed)
    }

    /// Give a tool a new id, leaving the old one resolving.
    ///
    /// The id *is* the tool's directory, so this moves it whole — the manifest and the owned
    /// script travel with it and nothing inside has to be rewritten — and then records the old id
    /// in the alias index. That second half is the point: a tool id is written down in places this
    /// crate cannot reach (an agent's `bin_tools`, a project's `.adi/hive.yaml`, a note, a shell
    /// history), and after this returns every one of them still names this tool.
    ///
    /// `from` may itself be an id the tool no longer has, so a rename can be corrected without
    /// first working out which id is current. Renaming to the id it already has is a no-op rather
    /// than an error: the caller asked for a state, and that state already holds.
    ///
    /// This is the *registry* half. Callers that own the whole store (`adi_core::rename_tool`)
    /// follow it into the agent definitions afterwards, so the new id is what those actually cost.
    ///
    /// A built-in **system** tool is protected, as it is from delete: its `sys-*` id is the handle
    /// the platform re-seeds it by ([`seed_system`](Self::seed_system)) and names in code, so a
    /// renamed one would simply be created again beside itself on the next start-up.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id on either side, [`Error::NotFound`] if `from` names
    /// no tool, [`Error::SystemProtected`] for a system tool, [`Error::Exists`] if anything
    /// already occupies `to`, or [`Error::Io`] / [`Error::Config`] if the move or the index write
    /// fails.
    pub fn rename(&self, from: &str, to: &str) -> Result<Tool> {
        validate_id(to)?;
        let tool = self.require(from)?;
        if tool.id == to {
            return Ok(tool);
        }
        if tool.is_system() {
            return Err(Error::SystemProtected(tool.id));
        }
        // Refuse an occupied directory, not just a registered tool: an unregistered `tools/<to>`
        // somebody made by hand would otherwise swallow the moved tool as a child of itself.
        if self.is_taken(to, &self.aliases()?) {
            return Err(Error::Exists(to.to_string()));
        }
        std::fs::rename(self.dir().join(&tool.id), self.dir().join(to))?;
        Aliases::record(&self.module(), &tool.id, to)?;
        self.sync_bin()?;
        Ok(Tool {
            id: to.to_string(),
            manifest: tool.manifest,
        })
    }

    /// Follow a project rename into this registry: every tool filed under `from` — archived ones
    /// too — is re-filed under `to`. Returns how many manifests changed.
    ///
    /// A project-scoped tool runs in its project's directory and against its project's database
    /// (see [`run`](Self::run) and `adi_config::Config::db_env`), so a tool left pointing at an id
    /// nothing answers to is a tool that runs in the wrong place. The shims are untouched: a
    /// tool's `.bin` name comes from its own name, never from its project.
    ///
    /// # Errors
    /// [`Error::Config`] if a manifest can't be written, plus everything [`list`](Self::list) can
    /// return.
    pub fn rename_project(&self, from: &str, to: &str) -> Result<usize> {
        let mut changed = 0;
        for mut tool in self.list()? {
            if tool.manifest.project.as_deref() != Some(from) {
                continue;
            }
            tool.manifest.project = Some(to.to_string());
            self.manifest_file(&tool.id).save(&tool.manifest)?;
            changed += 1;
        }
        Ok(changed)
    }

    /// Run a tool once and capture its combined output — the ▶ Run path. `working_dir` sets the
    /// process's cwd; `None` runs in the store root. `args` are forwarded to the script.
    ///
    /// # Errors
    /// [`Error::NotFound`] when unregistered, [`Error::LinkedMissing`] when the script is gone, or
    /// [`Error::Launch`] when the interpreter can't be spawned.
    pub fn run(
        &self,
        id: &str,
        args: &[String],
        working_dir: Option<&std::path::Path>,
    ) -> Result<RunOutput> {
        let tool = self.require(id)?;
        let script = self.script_path_of(&tool);
        let root = self.config.root().to_path_buf();
        let cwd = working_dir.unwrap_or(&root);
        run::run_capture(&tool, &script, args, cwd, &self.config)
    }

    /// Build the ready-to-spawn [`std::process::Command`] for a tool — the CLI's `tools run` path,
    /// which inherits the caller's stdio and forwards the exit code. Same resolution as
    /// [`run`](Self::run); the caller decides how to spawn it.
    ///
    /// # Errors
    /// [`Error::NotFound`] when unregistered, or [`Error::LinkedMissing`] when the script is gone.
    pub fn command(
        &self,
        id: &str,
        args: &[String],
        working_dir: Option<&std::path::Path>,
    ) -> Result<std::process::Command> {
        let tool = self.require(id)?;
        let script = self.script_path_of(&tool);
        let root = self.config.root().to_path_buf();
        let cwd = working_dir.unwrap_or(&root);
        run::command(&tool, &script, args, cwd, &self.config)
    }

    /// Ensure the built-in **system tools** exist — the adi-ecosystem CLIs (`adi-tasks`,
    /// `adi-projects`, …) that wrap `adi-mono` subcommands. Idempotent: a system tool is created
    /// (with its stable `sys-*` id, `system` flag, and wrapper script) only when absent, so a
    /// user's edits or a deliberate archive are preserved across calls. Returns whether anything
    /// was created. Does **not** regenerate any `.bin` — callers do that (see [`sync_bin`](Self::sync_bin)).
    ///
    /// # Errors
    /// [`Error::Config`]/[`Error::Io`] on a write failure.
    pub fn seed_system(&self) -> Result<bool> {
        let mut created = false;
        for sys in system::SYSTEM_TOOLS {
            let file = self.manifest_file(sys.id);
            if file.exists() {
                continue;
            }
            let manifest = Manifest {
                name: sys.name.to_string(),
                description: Some(sys.description.to_string()),
                runtime: RUNTIME_SH.to_string(),
                linked_path: None,
                project: None,
                system: true,
                created_at: now_unix(),
                archived_at: None,
            };
            file.save(&manifest)?;
            let tool = Tool {
                id: sys.id.to_string(),
                manifest,
            };
            write_file(&self.script_path_of(&tool), &sys.script())?;
            created = true;
        }
        Ok(created)
    }

    /// Regenerate the global `.bin` (`tools/.bin`): one `sh` shim per **active, global** tool —
    /// the seeded system tools plus any user tool that isn't filed under a project — each `exec`ing
    /// `adi-mono tools run <id>`. Project-scoped tools live only in their agents' bins (see
    /// [`sync_agent_bin`](Self::sync_agent_bin)), never here. Does not seed — call
    /// [`seed_system`](Self::seed_system) first (the platform does, at startup). Returns the written
    /// map (`shim name` → `tool id`); on a slug collision the lower id wins.
    ///
    /// # Errors
    /// [`Error::Io`] if the `.bin` directory can't be rebuilt.
    pub fn sync_bin(&self) -> Result<std::collections::BTreeMap<String, String>> {
        let tools: Vec<Tool> = self
            .list()?
            .into_iter()
            .filter(|t| !t.is_archived() && t.manifest.project.is_none())
            .collect();
        self.write_shims(&self.bin_dir(), &tools)
    }

    /// A single agent's own bin directory: `tools/.agent-bin/<agent>`. This is the directory an
    /// agent gets prepended to its `PATH`. Returns the path even if it doesn't exist yet.
    #[must_use]
    pub fn agent_bin_dir(&self, agent_name: &str) -> PathBuf {
        self.dir().join(AGENT_BIN_DIR).join(agent_name)
    }

    /// Materialize an agent's own bin dir and return it. It holds a shim for exactly the tools the
    /// agent has **enabled** — the ids in `enabled` (the agent's per-tool checkboxes) that are still
    /// registered and active. Nothing is force-fed: an agent gets a tool only when it's ticked on,
    /// system or user alike. An empty `enabled` yields an empty bin.
    ///
    /// # Errors
    /// [`Error::Io`] if the agent's bin dir can't be rebuilt, or [`Error::Config`] on a bad manifest.
    pub fn sync_agent_bin(&self, agent_name: &str, enabled: &[String]) -> Result<PathBuf> {
        let dir = self.agent_bin_dir(agent_name);
        let enabled = self.enabled_set(enabled)?;
        let tools: Vec<Tool> = self
            .list()?
            .into_iter()
            .filter(|t| !t.is_archived() && enabled.contains(&t.id))
            .collect();
        self.write_shims(&dir, &tools)?;
        Ok(dir)
    }

    /// The current ids an `enabled` list denotes — each entry put through the alias index, so a
    /// definition still naming a tool by the UUID it was created under selects the same tool it
    /// always did. Nothing else in a launch would say otherwise: the agent would simply start
    /// without a tool its own definition says it has.
    fn enabled_set(&self, enabled: &[String]) -> Result<std::collections::HashSet<String>> {
        let aliases = self.aliases()?;
        Ok(enabled
            .iter()
            .map(|id| aliases.target(id).unwrap_or(id).to_string())
            .collect())
    }

    /// What the tools in `enabled` say about themselves — one entry per tool an agent actually gets
    /// a shim for, in the same order and under the same names as [`sync_agent_bin`](Self::sync_agent_bin)
    /// writes them, so what the agent is told matches what it can run. Each tool is asked
    /// `llm help`, then `help`, then `--help`; see [`ToolHelp`].
    ///
    /// Best-effort throughout, because this feeds a prompt and must never fail a launch: an
    /// unreadable registry yields no entries, a tool that answers nothing is listed by name alone,
    /// and the whole sweep is bounded — tools not yet cached when the budget runs out are left for
    /// the next launch to pick up.
    #[must_use]
    pub fn help_for(&self, enabled: &[String]) -> Vec<ToolHelp> {
        let Ok(tools) = self.list() else {
            return Vec::new();
        };
        let Ok(enabled) = self.enabled_set(enabled) else {
            return Vec::new();
        };
        let deadline = std::time::Instant::now() + help::TOTAL_BUDGET;
        let tools_dir = self.dir();
        let mut out = Vec::new();
        let mut seen = std::collections::HashSet::new();
        for tool in tools
            .iter()
            .filter(|t| !t.is_archived() && enabled.contains(&t.id))
        {
            let name = tool.bin_name();
            // The same first-wins rule the shims are written under: a colliding second tool has no
            // shim, so telling the agent about it would name something it can't run.
            if !seen.insert(name.clone()) {
                continue;
            }
            let script = self.script_path_of(tool);
            let text = help::text(
                &tools_dir,
                tool,
                &script,
                |args| {
                    let args: Vec<String> = args.iter().map(ToString::to_string).collect();
                    run::command(tool, &script, &args, self.config.root(), &self.config).ok()
                },
                deadline,
            );
            out.push(ToolHelp {
                name,
                description: tool.manifest.description.clone(),
                help: text,
            });
        }
        out
    }

    /// Rebuild `dir` from scratch with one shim per tool in `tools` (assumed already filtered and
    /// sorted by id), first-wins on a slug collision. Returns the written map (`shim name` → id).
    fn write_shims(
        &self,
        dir: &Path,
        tools: &[Tool],
    ) -> Result<std::collections::BTreeMap<String, String>> {
        // Rebuild from scratch: remove any stale shims, then recreate the directory.
        let _ = std::fs::remove_dir_all(dir);
        std::fs::create_dir_all(dir)?;

        let mut written = std::collections::BTreeMap::new();
        for tool in tools {
            let name = tool.bin_name();
            // First (lowest-id) tool with a given shim name wins; skip a later collision.
            if written.contains_key(&name) {
                continue;
            }
            write_executable(&dir.join(&name), &shim(tool))?;
            written.insert(name, tool.id.clone());
        }
        Ok(written)
    }

    /// Load a tool, turning absence into [`Error::NotFound`].
    fn require(&self, id: &str) -> Result<Tool> {
        self.get(id)?.ok_or_else(|| Error::NotFound(id.to_string()))
    }
}

/// The `sh` shim written to `.bin/<name>` for `tool` — a thin delegator to the CLI, so every run
/// funnels through one place (identity env, cwd, logging can all live there).
fn shim(tool: &Tool) -> String {
    format!(
        "#!/bin/sh\n\
         # adi tool: {name} ({id})\n\
         # Generated by `adi-mono tools sync-bin` — edits here are overwritten.\n\
         exec adi-mono tools run {id} \"$@\"\n",
        name = tool.display_name(),
        id = tool.id,
    )
}

/// The starter script a freshly created owned tool gets, so ▶ Run does something on the first click.
///
/// It answers `llm help` from the outset, because that answer is what every agent enabling this
/// tool will be told about it (see [`help`]). Starting with the branch in place makes describing
/// the tool an edit rather than a thing to remember.
fn starter(runtime: &str, name: &str) -> String {
    match normalize_runtime(runtime) {
        RUNTIME_TS => format!(
            "#!/usr/bin/env bun\n\
             // {name} — an adi tool. Arguments arrive in Bun.argv.slice(2).\n\
             const args = Bun.argv.slice(2);\n\
             \n\
             // What agents are told about this tool: describe what it does, its commands and\n\
             // flags, what it prints, and one example. Keep it short.\n\
             if (args[0] === \"llm\" && args[1] === \"help\") {{\n\
             \x20 console.log(`{name} — TODO: say what this tool does.\n\
             \n\
             Usage: {name} <args…>`);\n\
             \x20 process.exit(0);\n\
             }}\n\
             \n\
             console.log(`hello from {name}`, args);\n"
        ),
        _ => format!(
            "#!/bin/sh\n\
             # {name} — an adi tool. Arguments arrive in \"$@\".\n\
             set -eu\n\
             \n\
             # What agents are told about this tool: describe what it does, its commands and\n\
             # flags, what it prints, and one example. Keep it short.\n\
             if [ \"${{1:-}}\" = \"llm\" ] && [ \"${{2:-}}\" = \"help\" ]; then\n\
             \x20 cat <<'HELP'\n\
             {name} — TODO: say what this tool does.\n\
             \n\
             Usage: {name} <args…>\n\
             HELP\n\
             \x20 exit 0\n\
             fi\n\
             \n\
             echo \"hello from {name} $*\"\n"
        ),
    }
}

/// Write `content` to `path`, creating any missing parent directories. Used for both the owned
/// script in the store and a linked tool's target file (the user edits it here).
fn write_file(path: &std::path::Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(())
}

/// Write `content` to `path` and mark it executable (`0o755` on Unix), creating parents. Used for
/// the `.bin` shims so an agent can run them directly.
fn write_executable(path: &std::path::Path, content: &str) -> Result<()> {
    write_file(path, content)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> Tools {
        let root = std::env::temp_dir().join(format!(
            "adi-tools-{tag}-{}-{:?}",
            std::process::id(),
            std::thread::current().id(),
        ));
        let _ = std::fs::remove_dir_all(&root);
        Tools::with_config(Config::with_root(root))
    }

    #[test]
    fn create_owned_then_get_list_and_read_script() {
        let store = scratch("owned");
        assert!(store.list().expect("empty").is_empty());

        let tool = store
            .create_file("Greet", Some("says hi".into()), "sh", None, None)
            .expect("create");
        assert_eq!(tool.manifest.name, "Greet");
        assert_eq!(tool.runtime(), "sh");
        assert!(!tool.is_linked());
        assert!(tool.manifest.created_at > 0);

        let got = store.get(&tool.id).expect("get").expect("present");
        assert_eq!(got, tool);
        assert_eq!(store.list().expect("list").len(), 1);

        // The starter script is written and readable.
        let body = store.read_script(&tool.id).expect("read");
        assert!(body.contains("hello from Greet"), "body was {body:?}");

        // Edit it, then read it back.
        store
            .write_script(&tool.id, "echo custom\n")
            .expect("write");
        assert_eq!(
            store.read_script(&tool.id).expect("reread"),
            "echo custom\n"
        );
    }

    /// The id is the name, so nothing has to carry a UUID around to say which tool it means.
    #[test]
    fn a_new_tools_id_is_a_slug_of_its_name() {
        let store = scratch("mint");
        let tool = store
            .create_file("Confirm Sync", None, "sh", None, None)
            .expect("create");
        assert_eq!(tool.id, "confirm-sync");
        assert!(store.tool_dir(&tool.id).expect("dir").is_dir());

        // A second tool of the same name takes the next number rather than the first one's dir.
        let again = store
            .create_file("confirm sync", None, "sh", None, None)
            .expect("create again");
        assert_eq!(again.id, "confirm-sync-2");

        // Nothing sluggable in the name: the kind's own word, then the same numbering.
        let cyrillic = store
            .create_file("Инструмент", None, "sh", None, None)
            .expect("create cyrillic");
        assert_eq!(cyrillic.id, "tool");
        let blank = store
            .create_file("  ", None, "sh", None, None)
            .expect("blank");
        assert_eq!(blank.id, "tool-2");
        assert_eq!(
            blank.manifest.name, "tool-2",
            "a blank name falls back to the id"
        );

        // A linked tool mints from the name it infers from the file, on the same rule.
        let target = store.dir().join("external").join("Build Thing.ts");
        std::fs::create_dir_all(target.parent().expect("parent")).expect("mkdir");
        std::fs::write(&target, "console.log(1)\n").expect("write");
        let linked = store
            .link(&target.to_string_lossy(), None, None, None, None)
            .expect("link");
        assert_eq!(linked.id, "build-thing");
    }

    /// The hard constraint of the whole change: after a rename the old id still names the tool.
    /// Agent definitions, generated shims and the operator's own notes all cite ids verbatim.
    #[test]
    fn a_renamed_tool_still_answers_to_the_id_it_had() {
        let store = scratch("rename");
        let uuid = "ec5bd98c-35c1-4e9e-ba25-5c2dbd3d5a99";
        let manifest = Manifest {
            name: "confirm-sync".into(),
            runtime: RUNTIME_SH.into(),
            created_at: now_unix(),
            ..Manifest::default()
        };
        store.manifest_file(uuid).save(&manifest).expect("seed");
        store.write_script(uuid, "printf ran\n").expect("script");

        let renamed = store.rename(uuid, "confirm-sync").expect("rename");
        assert_eq!(renamed.id, "confirm-sync");

        // Both ids resolve, to the same tool, with its script and its shim intact.
        let by_old = store.get(uuid).expect("get old").expect("present");
        let by_new = store
            .get("confirm-sync")
            .expect("get new")
            .expect("present");
        assert_eq!(by_old, by_new);
        assert_eq!(
            by_old.id, "confirm-sync",
            "the current id is what is reported"
        );
        assert_eq!(store.read_script(uuid).expect("script"), "printf ran\n");
        assert_eq!(store.run(uuid, &[], None).expect("run").output, "ran");
        assert!(store.bin_dir().join("confirm-sync").exists());

        // An agent definition that still names the UUID gets the same shim it always did.
        let dir = store
            .sync_agent_bin("adi-agent", &[uuid.to_string()])
            .expect("agent bin");
        assert!(
            dir.join("confirm-sync").exists(),
            "the old id lost the tool"
        );
        assert_eq!(store.help_for(&[uuid.to_string()]).len(), 1);

        // And the id it gave up is not free to be minted onto something else.
        let other = store
            .create_file("confirm sync", None, "sh", None, None)
            .expect("other");
        assert_eq!(other.id, "confirm-sync-2");
        assert_eq!(
            store.get(uuid).expect("get old").expect("present").id,
            "confirm-sync"
        );
    }

    /// A rename is correctable and idempotent, and it never lands on something already there.
    #[test]
    fn rename_is_guarded_and_reachable_through_an_old_id() {
        let store = scratch("rename-guard");
        let a = store.create_file("A", None, "sh", None, None).expect("a");
        store.create_file("B", None, "sh", None, None).expect("b");

        assert!(matches!(store.rename(&a.id, "b"), Err(Error::Exists(_))));
        assert!(matches!(
            store.rename("ghost", "c"),
            Err(Error::NotFound(_))
        ));
        assert!(matches!(
            store.rename(&a.id, "../x"),
            Err(Error::InvalidId(_))
        ));
        // Every refusal left both tools exactly where they were.
        assert!(store.get("a").expect("get a").is_some());
        assert!(store.get("b").expect("get b").is_some());

        store.rename("a", "first").expect("rename");
        // Correct it through the id it no longer has, then again through the one before that.
        store.rename("a", "second").expect("re-rename by old id");
        assert_eq!(store.get("a").expect("get").expect("present").id, "second");
        assert_eq!(
            store.get("first").expect("get").expect("present").id,
            "second"
        );
        // Renaming to the id it already has is a no-op, not an error.
        assert_eq!(store.rename("second", "second").expect("noop").id, "second");
    }

    /// A `sys-*` id is a compile-time handle (`SYS_KNOWLEDGE_ROOT`) and the key `seed_system`
    /// re-creates by, so a renamed system tool would be recreated beside itself on next start-up.
    #[test]
    fn a_system_tool_cannot_be_renamed() {
        let store = scratch("rename-sys");
        store.seed_system().expect("seed");
        assert!(matches!(
            store.rename("sys-tasks", "adi-tasks"),
            Err(Error::SystemProtected(_))
        ));
        assert!(store.get("sys-tasks").expect("get").is_some());
    }

    /// Deleting a tool releases the ids it answered to — an alias to nothing would keep an id
    /// reserved against a future mint while pointing at a tool that no longer exists.
    #[test]
    fn removing_a_tool_forgets_its_old_ids() {
        let store = scratch("rename-rm");
        store
            .create_file("Old Name", None, "sh", None, None)
            .expect("create");
        store.rename("old-name", "new-name").expect("rename");
        assert!(store.remove("old-name").expect("remove by old id"));
        assert!(store.get("new-name").expect("get").is_none());
        assert!(store.aliases().expect("aliases").all().is_empty());
        // Free again: a fresh tool may now take the id.
        let fresh = store
            .create_file("Old Name", None, "sh", None, None)
            .expect("fresh");
        assert_eq!(fresh.id, "old-name");
    }

    #[test]
    fn rename_project_refiles_that_projects_tools_and_nobody_elses() {
        let store = scratch("rename-project");
        let mine = store
            .create_file("Mine", None, "sh", Some("old".into()), None)
            .expect("mine");
        let archived = store
            .create_file("Archived", None, "sh", Some("old".into()), None)
            .expect("archived");
        store.archive(&archived.id).expect("archive");
        let theirs = store
            .create_file("Theirs", None, "sh", Some("other".into()), None)
            .expect("theirs");
        let global = store
            .create_file("Global", None, "sh", None, None)
            .expect("global");

        assert_eq!(store.rename_project("old", "new").expect("rename"), 2);
        let project_of = |id: &str| {
            store
                .get(id)
                .expect("get")
                .expect("present")
                .manifest
                .project
        };
        assert_eq!(project_of(&mine.id).as_deref(), Some("new"));
        assert_eq!(project_of(&archived.id).as_deref(), Some("new"));
        assert_eq!(project_of(&theirs.id).as_deref(), Some("other"));
        assert_eq!(project_of(&global.id), None);

        // Nothing left to follow the second time.
        assert_eq!(store.rename_project("old", "new").expect("again"), 0);
    }

    #[test]
    fn owned_script_lands_at_the_runtime_extension() {
        let store = scratch("ext");
        let sh = store.create_file("s", None, "sh", None, None).expect("sh");
        assert!(
            store
                .script_path(&sh.id)
                .expect("path")
                .ends_with("script.sh")
        );
        let ts = store.create_file("t", None, "ts", None, None).expect("ts");
        assert!(
            store
                .script_path(&ts.id)
                .expect("path")
                .ends_with("script.ts")
        );
    }

    #[test]
    fn an_unknown_runtime_is_refused() {
        let store = scratch("badruntime");
        assert!(matches!(
            store.create_file("x", None, "perl", None, None),
            Err(Error::InvalidRuntime(_))
        ));
    }

    #[test]
    fn link_points_at_an_existing_file_and_infers_runtime() {
        let store = scratch("link");
        let dir = store.dir().join("external");
        std::fs::create_dir_all(&dir).expect("mkdir");
        let target = dir.join("build.ts");
        std::fs::write(&target, "console.log('x')\n").expect("write target");

        let tool = store
            .link(&target.to_string_lossy(), None, None, None, None)
            .expect("link");
        assert!(tool.is_linked());
        assert_eq!(tool.manifest.name, "build");
        assert_eq!(tool.runtime(), "ts");
        // Reads through to the linked file.
        assert_eq!(
            store.read_script(&tool.id).expect("read"),
            "console.log('x')\n"
        );

        // Removing a linked tool never deletes the target file.
        assert!(store.remove(&tool.id).expect("remove"));
        assert!(target.exists(), "linked target must survive removal");
    }

    #[test]
    fn linking_a_missing_path_is_refused() {
        let store = scratch("linkmissing");
        assert!(matches!(
            store.link("/no/such/file-xyz", None, None, None, None),
            Err(Error::LinkedMissing(_))
        ));
    }

    #[test]
    fn archive_toggles_state_and_bin_shim() {
        let store = scratch("archive");
        let tool = store
            .create_file("deploy", None, "sh", None, None)
            .expect("create");
        let shim = store.bin_dir().join("deploy");
        assert!(shim.exists(), "active tool should have a .bin shim");

        let archived = store.archive(&tool.id).expect("archive");
        assert!(archived.is_archived());
        assert!(!shim.exists(), "archived tool's shim should be gone");

        let restored = store.unarchive(&tool.id).expect("unarchive");
        assert!(!restored.is_archived());
        assert!(shim.exists(), "restored tool's shim should return");
    }

    #[test]
    fn bin_shim_delegates_to_the_cli_run() {
        let store = scratch("shim");
        let tool = store
            .create_file("My Tool", None, "sh", None, None)
            .expect("create");
        let shim = store.bin_dir().join("my-tool");
        let body = std::fs::read_to_string(&shim).expect("shim");
        assert!(
            body.contains(&format!("adi-mono tools run {}", tool.id)),
            "shim: {body}"
        );
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt as _;
            let mode = std::fs::metadata(&shim).expect("meta").permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "shim must be executable");
        }
    }

    #[test]
    fn colliding_bin_names_keep_the_lower_id() {
        let store = scratch("collide");
        // Two tools whose names slug to the same shim name.
        let a = store
            .create_file("Same Name", None, "sh", None, None)
            .expect("a");
        let b = store
            .create_file("same-name", None, "sh", None, None)
            .expect("b");
        let map = store.sync_bin().expect("sync");
        let winner = map.get("same-name").expect("a shim named same-name");
        let lower = std::cmp::min(a.id.clone(), b.id.clone());
        assert_eq!(winner, &lower, "lower id wins the shim");
    }

    #[test]
    fn seed_system_is_idempotent_and_flags_system_tools() {
        let store = scratch("seed");
        assert!(
            store.seed_system().expect("seed"),
            "first seed creates tools"
        );
        assert!(
            !store.seed_system().expect("reseed"),
            "second seed is a no-op"
        );
        let tools = store.list().expect("list");
        assert!(!tools.is_empty());
        assert!(tools.iter().all(|t| t.is_system()), "all seeded are system");
        // A known one wraps its adi-mono subcommand.
        let tasks = store.get("sys-tasks").expect("get").expect("present");
        assert!(tasks.is_system());
        assert_eq!(tasks.manifest.name, "adi-tasks");
        assert!(
            store
                .read_script("sys-tasks")
                .expect("script")
                .contains("adi-mono tasks")
        );
    }

    /// The knowledge base is only reachable by an agent if it has a `.bin` for it — a subcommand
    /// nothing seeds a shim for is a subcommand no agent can run.
    #[test]
    fn the_knowledge_base_is_one_of_the_tools_every_agent_can_have() {
        let store = scratch("knowledge");
        store.seed_system().expect("seed");

        let tool = store.get("sys-knowledge").expect("get").expect("present");
        assert!(tool.is_system());
        assert_eq!(tool.manifest.name, "adi-knowledge");
        assert!(
            store
                .read_script("sys-knowledge")
                .expect("script")
                .contains("adi-mono knowledge")
        );

        let dir = store
            .sync_agent_bin("solver", &["sys-knowledge".to_string()])
            .expect("agent bin");
        assert!(dir.join("adi-knowledge").exists(), "no shim to run it by");
    }

    /// The root variant is a separate tool over the same subcommand, and the `--root` in its script
    /// is the whole of the difference — without it the shim is plain `adi-knowledge` under another
    /// name, and the one thing it exists for (writing into another agent's memory) silently fails
    /// the isolation check instead.
    #[test]
    fn the_root_knowledge_shim_carries_the_flag_that_makes_it_root() {
        let store = scratch("knowledge-root");
        store.seed_system().expect("seed");

        let tool = store
            .get(SYS_KNOWLEDGE_ROOT)
            .expect("get")
            .expect("present");
        assert!(tool.is_system());
        assert_eq!(tool.manifest.name, "adi-knowledge-root");
        assert!(
            store
                .read_script(SYS_KNOWLEDGE_ROOT)
                .expect("script")
                .contains("adi-mono knowledge --root")
        );

        // Ticking one does not tick the other: an agent gets root because somebody gave it root.
        let dir = store
            .sync_agent_bin("reviewer", &[SYS_KNOWLEDGE_ROOT.to_string()])
            .expect("agent bin");
        assert!(
            dir.join("adi-knowledge-root").exists(),
            "no shim to run it by"
        );
        assert!(
            !dir.join("adi-knowledge").exists(),
            "the plain tool arrived on its own"
        );
    }

    #[test]
    fn a_system_tool_cannot_be_hard_deleted() {
        let store = scratch("sysdel");
        store.seed_system().expect("seed");
        assert!(matches!(
            store.remove("sys-tasks"),
            Err(Error::SystemProtected(_))
        ));
        // But it can be archived (to disable it).
        assert!(store.archive("sys-tasks").expect("archive").is_archived());
    }

    #[test]
    fn agent_bin_holds_only_the_enabled_tools() {
        let store = scratch("agentbin");
        store.seed_system().expect("seed");
        let mine = store
            .create_file("mine", None, "sh", None, None)
            .expect("mine");
        let other = store
            .create_file("other", None, "sh", None, None)
            .expect("other");

        // Enable one user tool + one system tool; the other user tool is left off.
        let enabled = vec![mine.id.clone(), "sys-tasks".to_string()];
        let dir = store.sync_agent_bin("solver", &enabled).expect("agent bin");
        assert!(dir.ends_with(".agent-bin/solver"), "got {}", dir.display());
        assert!(dir.join("mine").exists(), "enabled user tool present");
        assert!(
            dir.join("adi-tasks").exists(),
            "enabled system tool present"
        );
        assert!(!dir.join("other").exists(), "unselected tool absent");

        // An empty selection yields an empty bin (nothing force-fed).
        let empty = store.sync_agent_bin("bare", &[]).expect("empty");
        assert_eq!(std::fs::read_dir(&empty).expect("read").count(), 0);
        let _ = other;
    }

    #[test]
    fn run_executes_and_captures_output() {
        let store = scratch("run");
        let tool = store
            .create_file("echoer", None, "sh", None, None)
            .expect("create");
        store
            .write_script(&tool.id, "printf 'ran:%s' \"$1\"\n")
            .expect("write");
        let out = store.run(&tool.id, &["ok".to_string()], None).expect("run");
        assert!(out.ok());
        assert_eq!(out.output, "ran:ok");
    }

    /// A tool describes itself from the moment it is created: the starter answers `llm help`, so
    /// enabling a brand-new tool on an agent already puts something real in that agent's prompt —
    /// a `TODO` to replace, rather than silence to notice.
    #[test]
    fn a_new_tool_answers_llm_help_out_of_the_box() {
        let store = scratch("starter-help");
        let tool = store
            .create_file("greet", Some("Say hello.".into()), "sh", None, None)
            .expect("create");

        let described = store.help_for(&[tool.id.clone()]);
        assert_eq!(described.len(), 1);
        assert_eq!(described[0].name, "greet");
        assert_eq!(described[0].description.as_deref(), Some("Say hello."));
        let help = described[0]
            .help
            .as_deref()
            .expect("the starter's own help");
        assert!(help.starts_with("greet —"), "{help}");
        assert!(help.contains("Usage: greet"), "{help}");

        // The `ts` starter carries the same branch; running it would need bun, so read the script.
        let ts = store
            .create_file("greet-ts", None, "ts", None, None)
            .expect("create");
        let script = store.read_script(&ts.id).expect("read");
        assert!(script.contains(r#"args[0] === "llm""#), "{script}");
    }

    /// A tool enabled on nothing is asked nothing, and an unregistered id contributes no entry —
    /// the two ways a prompt would otherwise gain a command that isn't there.
    #[test]
    fn help_covers_exactly_the_enabled_registered_tools() {
        let store = scratch("help-scope");
        let tool = store
            .create_file("greet", None, "sh", None, None)
            .expect("create");
        assert!(store.help_for(&[]).is_empty());
        assert!(store.help_for(&["ghost".to_string()]).is_empty());

        store.archive(&tool.id).expect("archive");
        assert!(
            store.help_for(&[tool.id]).is_empty(),
            "an archived tool has no shim, so it must not be described"
        );
    }

    #[test]
    fn mutating_an_unregistered_tool_is_not_found() {
        let store = scratch("missing");
        assert!(matches!(store.archive("ghost"), Err(Error::NotFound(_))));
        assert!(matches!(
            store.read_script("ghost"),
            Err(Error::NotFound(_))
        ));
        assert!(store.get("ghost").expect("get").is_none());
        assert!(!store.remove("ghost").expect("remove missing"));
    }

    #[test]
    fn invalid_ids_never_touch_disk() {
        let store = scratch("invalid");
        assert!(matches!(store.get("../escape"), Err(Error::InvalidId(_))));
        assert!(matches!(store.remove(".."), Err(Error::InvalidId(_))));
        assert!(matches!(store.tool_dir("a/b"), Err(Error::InvalidId(_))));
    }

    #[test]
    fn list_skips_the_bin_dir_and_dirs_without_a_manifest() {
        let store = scratch("skip");
        store
            .create_file("real", None, "sh", None, None)
            .expect("create");
        std::fs::create_dir_all(store.dir().join("bare")).expect("mkdir");
        let all = store.list().expect("list");
        assert_eq!(all.len(), 1, "only the real tool is listed");
        assert_eq!(all[0].manifest.name, "real");
    }
}
