//! adi-tools — register, edit, and run *tools*: small CLIs an agent invokes. A pure library
//! (no CLI, no daemon) over the shared [`adi_config`] store, mirroring [`adi_projects`].
//!
//! Each tool is a directory under `~/.adi/mono/tools/<id>/` whose `config.toml` is a metadata
//! [`Manifest`]. A tool is either:
//!
//! * **owned** — its script lives in the store at `tools/<id>/script.<ext>`, created and edited
//!   through here; or
//! * **linked** — [`Manifest::linked_path`] points at an existing file on disk, which the store
//!   reads and (optionally) writes through to but never copies or deletes.
//!
//! Every active tool is also exposed as a `tools/.bin/<name>` shim — a tiny `sh` script that
//! `exec`s `adi-mono tools run <id> "$@"` — so an agent with that `.bin` on its `PATH` runs a
//! tool by name. The shims are regenerated from the manifests on every mutation.
//!
//! ```
//! # let tmp = std::env::temp_dir().join(format!("adi-tools-doctest-{}", std::process::id()));
//! # let _ = std::fs::remove_dir_all(&tmp);
//! use adi_tools::Tools;
//!
//! # let store = Tools::with_config(adi_config::Config::with_root(&tmp));
//! // In real code: let store = Tools::open();
//! let tool = store.create_file("greet", None, "sh", None, Some("echo hi\n".into()))?;
//! assert_eq!(tool.manifest.name, "greet");
//! assert!(!tool.is_linked());
//! assert_eq!(store.read_script(&tool.id)?.trim(), "echo hi");
//!
//! store.archive(&tool.id)?;
//! assert!(store.get(&tool.id)?.unwrap().is_archived());
//! # std::fs::remove_dir_all(&tmp).ok();
//! # Ok::<(), adi_tools::Error>(())
//! ```

mod error;
mod run;
mod system;
mod tool;

use std::path::{Path, PathBuf};

use adi_config::{Config, ConfigFile, now_unix};

pub use error::{Error, Result};
pub use run::RunOutput;
pub use tool::{
    Manifest, RUNTIME_SH, RUNTIME_TS, Tool, normalize_runtime, runtime_ext, runtime_from_path,
    validate_runtime,
};

use tool::validate_id;

/// The store module tools live under, the manifest file within each tool dir, the owned-script
/// stem, and the shim directory agents put on their `PATH`.
const TOOLS_MODULE: &str = "tools";
const MANIFEST_FILE: &str = "config.toml";
const SCRIPT_STEM: &str = "script";
const BIN_DIR: &str = ".bin";
/// The parent of the per-agent bin dirs (`tools/.agent-bin/<agent>`). Dot-prefixed so
/// [`Tools::list`] skips it, and separate from [`BIN_DIR`] so regenerating one never wipes the other.
const AGENT_BIN_DIR: &str = ".agent-bin";

/// The tools registry: lists, reads, edits, and runs the per-tool manifests + scripts under the
/// `tools` module dir. Cheap to clone; all state is on disk.
#[derive(Debug, Clone)]
pub struct Tools {
    config: Config,
}

impl Default for Tools {
    fn default() -> Self {
        Self::open()
    }
}

impl Tools {
    /// Open the registry backed by the standard store (`~/.adi/mono`, honoring `$ADI_DIR`).
    #[must_use]
    pub fn open() -> Self {
        Self {
            config: Config::open(),
        }
    }

    /// Open the registry backed by a caller-supplied [`Config`] — for tests or alternate installs.
    #[must_use]
    pub fn with_config(config: Config) -> Self {
        Self { config }
    }

    /// The store this registry reads from.
    #[must_use]
    pub fn config(&self) -> &Config {
        &self.config
    }

    /// The `tools` directory: `~/.adi/mono/tools`.
    #[must_use]
    pub fn dir(&self) -> PathBuf {
        self.config.module(TOOLS_MODULE).dir().to_path_buf()
    }

    /// The shim directory agents add to their `PATH`: `~/.adi/mono/tools/.bin`. Holds one
    /// `sh` shim per active tool (regenerated by [`sync_bin`](Self::sync_bin)).
    #[must_use]
    pub fn bin_dir(&self) -> PathBuf {
        self.dir().join(BIN_DIR)
    }

    /// A tool's own directory: `tools/<id>`. Returns the path even if it doesn't exist yet.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id — the security boundary before the id is joined onto
    /// the store path.
    pub fn tool_dir(&self, id: &str) -> Result<PathBuf> {
        validate_id(id)?;
        Ok(self.dir().join(id))
    }

    /// The manifest file handle for `id`, at `tools/<id>/config.toml` (touches no disk).
    fn manifest_file(&self, id: &str) -> ConfigFile<Manifest> {
        self.config
            .module(TOOLS_MODULE)
            .file(&format!("{id}/{MANIFEST_FILE}"))
    }

    /// Where a tool's script lives: the linked file for a linked tool, else the owned
    /// `tools/<id>/script.<ext>` in the store. Returns the path even if it doesn't exist.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id, [`Error::NotFound`] when the tool isn't registered.
    pub fn script_path(&self, id: &str) -> Result<PathBuf> {
        let tool = self.require(id)?;
        Ok(self.script_path_of(&tool))
    }

    /// The script path of an already-loaded tool (no disk read) — see [`script_path`](Self::script_path).
    fn script_path_of(&self, tool: &Tool) -> PathBuf {
        match &tool.manifest.linked_path {
            Some(path) => PathBuf::from(path),
            None => self
                .dir()
                .join(&tool.id)
                .join(format!("{SCRIPT_STEM}.{}", runtime_ext(&tool.manifest.runtime))),
        }
    }

    /// Every registered tool, sorted by id. A tool dir without a `config.toml` isn't registered
    /// yet and is skipped; a missing `tools/` dir yields an empty list.
    ///
    /// # Errors
    /// [`Error::Io`] on a directory read failure, or [`Error::Config`] if a manifest is invalid TOML.
    pub fn list(&self) -> Result<Vec<Tool>> {
        let Some(entries) = optional(std::fs::read_dir(self.dir()))? else {
            return Ok(Vec::new());
        };

        let mut tools = Vec::new();
        for entry in entries {
            let entry = entry?;
            if !entry.file_type()?.is_dir() {
                continue;
            }
            let Ok(id) = entry.file_name().into_string() else {
                continue;
            };
            // The `.bin` shim dir (and any other dotfile) is not a tool.
            if id.starts_with('.') || validate_id(&id).is_err() {
                continue;
            }
            let file = self.manifest_file(&id);
            if !file.exists() {
                continue;
            }
            tools.push(Tool {
                id,
                manifest: file.load()?,
            });
        }
        tools.sort_by(|a, b| a.id.cmp(&b.id));
        Ok(tools)
    }

    /// The tool with this id, or `None` if it isn't registered.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id, or [`Error::Config`] if the manifest is invalid TOML.
    pub fn get(&self, id: &str) -> Result<Option<Tool>> {
        validate_id(id)?;
        let file = self.manifest_file(id);
        if !file.exists() {
            return Ok(None);
        }
        Ok(Some(Tool {
            id: id.to_string(),
            manifest: file.load()?,
        }))
    }

    /// Register a new **owned** tool under a generated UUID id: writes its `config.toml` and an
    /// executable script (from `content`, or a runtime starter when omitted), then regenerates the
    /// `.bin` shims. A blank `name` falls back to the generated id.
    ///
    /// # Errors
    /// [`Error::InvalidRuntime`] for an unknown runtime, or [`Error::Config`]/[`Error::Io`] on a
    /// write failure.
    pub fn create_file(
        &self,
        name: &str,
        description: Option<String>,
        runtime: &str,
        project: Option<String>,
        content: Option<String>,
    ) -> Result<Tool> {
        let runtime = validate_runtime(runtime)?;
        let id = uuid::Uuid::new_v4().to_string();
        let name = clean(Some(name.to_string()));
        let manifest = Manifest {
            name: name.clone().unwrap_or_else(|| id.clone()),
            description: clean(description),
            runtime: runtime.to_string(),
            linked_path: None,
            project: clean(project),
            system: false,
            created_at: now_unix(),
            archived_at: None,
        };
        let tool = Tool {
            id: id.clone(),
            manifest,
        };
        self.manifest_file(&id).save(&tool.manifest)?;
        let body = content.unwrap_or_else(|| starter(runtime, tool.display_name()));
        write_file(&self.script_path_of(&tool), &body)?;
        self.sync_bin()?;
        Ok(tool)
    }

    /// Register a new **linked** tool that points at an existing file `path` on disk: writes only
    /// a manifest (the file is never copied), then regenerates the `.bin` shims. `name` defaults
    /// to the file's stem, `runtime` is inferred from the extension when blank.
    ///
    /// # Errors
    /// [`Error::LinkedMissing`] when `path` doesn't exist, [`Error::InvalidRuntime`] for an
    /// explicit unknown runtime, or [`Error::Config`]/[`Error::Io`] on a write failure.
    pub fn link(
        &self,
        path: &str,
        name: Option<String>,
        runtime: Option<String>,
        description: Option<String>,
        project: Option<String>,
    ) -> Result<Tool> {
        let raw = PathBuf::from(path.trim());
        if !raw.exists() {
            return Err(Error::LinkedMissing(raw.display().to_string()));
        }
        // Store an absolute path so the shim/run resolve it regardless of the caller's cwd.
        let abs = std::fs::canonicalize(&raw).unwrap_or(raw);
        let runtime = match runtime.as_deref().map(str::trim).filter(|r| !r.is_empty()) {
            Some(r) => validate_runtime(r)?.to_string(),
            None => runtime_from_path(&abs.to_string_lossy()).to_string(),
        };
        let name = clean(name).unwrap_or_else(|| {
            abs.file_stem()
                .map(|s| s.to_string_lossy().into_owned())
                .unwrap_or_else(|| "tool".to_string())
        });

        let id = uuid::Uuid::new_v4().to_string();
        let manifest = Manifest {
            name,
            description: clean(description),
            runtime,
            linked_path: Some(abs.display().to_string()),
            project: clean(project),
            system: false,
            created_at: now_unix(),
            archived_at: None,
        };
        self.manifest_file(&id).save(&manifest)?;
        self.sync_bin()?;
        Ok(Tool { id, manifest })
    }

    /// The tool's script text — the owned `script.<ext>`, or the linked file's contents.
    ///
    /// # Errors
    /// [`Error::NotFound`] when unregistered, [`Error::LinkedMissing`] when a linked file is gone,
    /// or [`Error::Io`] on a read failure.
    pub fn read_script(&self, id: &str) -> Result<String> {
        let path = self.script_path(id)?;
        match std::fs::read_to_string(&path) {
            Ok(text) => Ok(text),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                Err(Error::LinkedMissing(path.display().to_string()))
            }
            Err(e) => Err(Error::Io(e)),
        }
    }

    /// Overwrite the tool's script — the owned `script.<ext>` in the store, or (for a linked tool)
    /// the linked file itself, since the user linked it to edit it here.
    ///
    /// # Errors
    /// [`Error::NotFound`] when unregistered, or [`Error::Io`] on a write failure.
    pub fn write_script(&self, id: &str, content: &str) -> Result<()> {
        let path = self.script_path(id)?;
        write_file(&path, content)
    }

    /// Archive a tool (soft delete), stamping `archived_at` and dropping its `.bin` shim so it can
    /// no longer be run by name. Idempotent: re-archiving keeps the original timestamp.
    ///
    /// # Errors
    /// [`Error::NotFound`] if unregistered, plus the usual id/config/io errors.
    pub fn archive(&self, id: &str) -> Result<Tool> {
        let mut tool = self.require(id)?;
        if tool.manifest.archived_at.is_none() {
            tool.manifest.archived_at = Some(now_unix());
            self.manifest_file(id).save(&tool.manifest)?;
            self.sync_bin()?;
        }
        Ok(tool)
    }

    /// Restore an archived tool, clearing `archived_at` and re-creating its `.bin` shim.
    /// Idempotent for an active tool.
    ///
    /// # Errors
    /// [`Error::NotFound`] if unregistered, plus the usual id/config/io errors.
    pub fn unarchive(&self, id: &str) -> Result<Tool> {
        let mut tool = self.require(id)?;
        if tool.manifest.archived_at.is_some() {
            tool.manifest.archived_at = None;
            self.manifest_file(id).save(&tool.manifest)?;
            self.sync_bin()?;
        }
        Ok(tool)
    }

    /// Permanently delete a tool's directory (its manifest and, for an owned tool, its script),
    /// then regenerate the `.bin` shims. A **linked** tool's target file is never touched — only
    /// the store's manifest dir is removed. A built-in **system** tool is protected: it cannot be
    /// hard-deleted (archive it to disable it instead). Returns `false` if the tool wasn't there.
    ///
    /// # Errors
    /// [`Error::InvalidId`] for an unsafe id, [`Error::SystemProtected`] for a system tool, or
    /// [`Error::Io`] on a removal failure.
    pub fn remove(&self, id: &str) -> Result<bool> {
        validate_id(id)?;
        if self.get(id)?.is_some_and(|t| t.is_system()) {
            return Err(Error::SystemProtected(id.to_string()));
        }
        let dir = self.dir().join(id);
        let removed = optional(std::fs::remove_dir_all(&dir))?.is_some();
        if removed {
            self.sync_bin()?;
        }
        Ok(removed)
    }

    /// Run a tool once and capture its combined output — the ▶ Run path. `working_dir` sets the
    /// process's cwd; `None` runs in the store root. `args` are forwarded to the script.
    ///
    /// # Errors
    /// [`Error::NotFound`] when unregistered, [`Error::LinkedMissing`] when the script is gone, or
    /// [`Error::Launch`] when the interpreter can't be spawned.
    pub fn run(
        &self,
        id: &str,
        args: &[String],
        working_dir: Option<&std::path::Path>,
    ) -> Result<RunOutput> {
        let tool = self.require(id)?;
        let script = self.script_path_of(&tool);
        let root = self.config.root().to_path_buf();
        let cwd = working_dir.unwrap_or(&root);
        run::run_capture(&tool, &script, args, cwd)
    }

    /// Build the ready-to-spawn [`std::process::Command`] for a tool — the CLI's `tools run` path,
    /// which inherits the caller's stdio and forwards the exit code. Same resolution as
    /// [`run`](Self::run); the caller decides how to spawn it.
    ///
    /// # Errors
    /// [`Error::NotFound`] when unregistered, or [`Error::LinkedMissing`] when the script is gone.
    pub fn command(
        &self,
        id: &str,
        args: &[String],
        working_dir: Option<&std::path::Path>,
    ) -> Result<std::process::Command> {
        let tool = self.require(id)?;
        let script = self.script_path_of(&tool);
        let root = self.config.root().to_path_buf();
        let cwd = working_dir.unwrap_or(&root);
        run::command(&tool, &script, args, cwd)
    }

    /// Ensure the built-in **system tools** exist — the adi-ecosystem CLIs (`adi-tasks`,
    /// `adi-projects`, …) that wrap `adi-mono` subcommands. Idempotent: a system tool is created
    /// (with its stable `sys-*` id, `system` flag, and wrapper script) only when absent, so a
    /// user's edits or a deliberate archive are preserved across calls. Returns whether anything
    /// was created. Does **not** regenerate any `.bin` — callers do that (see [`sync_bin`](Self::sync_bin)).
    ///
    /// # Errors
    /// [`Error::Config`]/[`Error::Io`] on a write failure.
    pub fn seed_system(&self) -> Result<bool> {
        let mut created = false;
        for sys in system::SYSTEM_TOOLS {
            let file = self.manifest_file(sys.id);
            if file.exists() {
                continue;
            }
            let manifest = Manifest {
                name: sys.name.to_string(),
                description: Some(sys.description.to_string()),
                runtime: RUNTIME_SH.to_string(),
                linked_path: None,
                project: None,
                system: true,
                created_at: now_unix(),
                archived_at: None,
            };
            file.save(&manifest)?;
            let tool = Tool {
                id: sys.id.to_string(),
                manifest,
            };
            write_file(&self.script_path_of(&tool), &sys.script())?;
            created = true;
        }
        Ok(created)
    }

    /// Regenerate the global `.bin` (`tools/.bin`): one `sh` shim per **active, global** tool —
    /// the seeded system tools plus any user tool that isn't filed under a project — each `exec`ing
    /// `adi-mono tools run <id>`. Project-scoped tools live only in their agents' bins (see
    /// [`sync_agent_bin`](Self::sync_agent_bin)), never here. Does not seed — call
    /// [`seed_system`](Self::seed_system) first (the platform does, at startup). Returns the written
    /// map (`shim name` → `tool id`); on a slug collision the lower id wins.
    ///
    /// # Errors
    /// [`Error::Io`] if the `.bin` directory can't be rebuilt.
    pub fn sync_bin(&self) -> Result<std::collections::BTreeMap<String, String>> {
        let tools: Vec<Tool> = self
            .list()?
            .into_iter()
            .filter(|t| !t.is_archived() && t.manifest.project.is_none())
            .collect();
        self.write_shims(&self.bin_dir(), &tools)
    }

    /// A single agent's own bin directory: `tools/.agent-bin/<agent>`. This is the directory an
    /// agent gets prepended to its `PATH`. Returns the path even if it doesn't exist yet.
    #[must_use]
    pub fn agent_bin_dir(&self, agent_name: &str) -> PathBuf {
        self.dir().join(AGENT_BIN_DIR).join(agent_name)
    }

    /// Materialize an agent's own bin dir and return it. It holds a shim for exactly the tools the
    /// agent has **enabled** — the ids in `enabled` (the agent's per-tool checkboxes) that are still
    /// registered and active. Nothing is force-fed: an agent gets a tool only when it's ticked on,
    /// system or user alike. An empty `enabled` yields an empty bin.
    ///
    /// # Errors
    /// [`Error::Io`] if the agent's bin dir can't be rebuilt, or [`Error::Config`] on a bad manifest.
    pub fn sync_agent_bin(&self, agent_name: &str, enabled: &[String]) -> Result<PathBuf> {
        let dir = self.agent_bin_dir(agent_name);
        let enabled: std::collections::HashSet<&str> =
            enabled.iter().map(String::as_str).collect();
        let tools: Vec<Tool> = self
            .list()?
            .into_iter()
            .filter(|t| !t.is_archived() && enabled.contains(t.id.as_str()))
            .collect();
        self.write_shims(&dir, &tools)?;
        Ok(dir)
    }

    /// Rebuild `dir` from scratch with one shim per tool in `tools` (assumed already filtered and
    /// sorted by id), first-wins on a slug collision. Returns the written map (`shim name` → id).
    fn write_shims(
        &self,
        dir: &Path,
        tools: &[Tool],
    ) -> Result<std::collections::BTreeMap<String, String>> {
        // Rebuild from scratch: remove any stale shims, then recreate the directory.
        let _ = std::fs::remove_dir_all(dir);
        std::fs::create_dir_all(dir)?;

        let mut written = std::collections::BTreeMap::new();
        for tool in tools {
            let name = tool.bin_name();
            // First (lowest-id) tool with a given shim name wins; skip a later collision.
            if written.contains_key(&name) {
                continue;
            }
            write_executable(&dir.join(&name), &shim(tool))?;
            written.insert(name, tool.id.clone());
        }
        Ok(written)
    }

    /// Load a tool, turning absence into [`Error::NotFound`].
    fn require(&self, id: &str) -> Result<Tool> {
        self.get(id)?.ok_or_else(|| Error::NotFound(id.to_string()))
    }
}

/// The `sh` shim written to `.bin/<name>` for `tool` — a thin delegator to the CLI, so every run
/// funnels through one place (identity env, cwd, logging can all live there).
fn shim(tool: &Tool) -> String {
    format!(
        "#!/bin/sh\n\
         # adi tool: {name} ({id})\n\
         # Generated by `adi-mono tools sync-bin` — edits here are overwritten.\n\
         exec adi-mono tools run {id} \"$@\"\n",
        name = tool.display_name(),
        id = tool.id,
    )
}

/// The starter script a freshly created owned tool gets, so ▶ Run does something on the first click.
fn starter(runtime: &str, name: &str) -> String {
    match normalize_runtime(runtime) {
        RUNTIME_TS => format!(
            "#!/usr/bin/env bun\n\
             // {name} — an adi tool. Arguments arrive in Bun.argv.slice(2).\n\
             const args = Bun.argv.slice(2);\n\
             console.log(`hello from {name}`, args);\n"
        ),
        _ => format!(
            "#!/bin/sh\n\
             # {name} — an adi tool. Arguments arrive in \"$@\".\n\
             set -eu\n\
             echo \"hello from {name} $*\"\n"
        ),
    }
}

/// Write `content` to `path`, creating any missing parent directories. Used for both the owned
/// script in the store and a linked tool's target file (the user edits it here).
fn write_file(path: &std::path::Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;
    Ok(())
}

/// Write `content` to `path` and mark it executable (`0o755` on Unix), creating parents. Used for
/// the `.bin` shims so an agent can run them directly.
fn write_executable(path: &std::path::Path, content: &str) -> Result<()> {
    write_file(path, content)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o755))?;
    }
    Ok(())
}

/// Fold a "not found" I/O error into `Ok(None)`, propagating any other failure as [`Error::Io`].
fn optional<T>(result: std::io::Result<T>) -> Result<Option<T>> {
    match result {
        Ok(value) => Ok(Some(value)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(Error::Io(e)),
    }
}

/// Trim a string, dropping it entirely when blank.
fn clean(value: Option<String>) -> Option<String> {
    value
        .map(|v| v.trim().to_string())
        .filter(|v| !v.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> Tools {
        let root = std::env::temp_dir().join(format!(
            "adi-tools-{tag}-{}-{:?}",
            std::process::id(),
            std::thread::current().id(),
        ));
        let _ = std::fs::remove_dir_all(&root);
        Tools::with_config(Config::with_root(root))
    }

    #[test]
    fn create_owned_then_get_list_and_read_script() {
        let store = scratch("owned");
        assert!(store.list().expect("empty").is_empty());

        let tool = store
            .create_file("Greet", Some("says hi".into()), "sh", None, None)
            .expect("create");
        assert_eq!(tool.manifest.name, "Greet");
        assert_eq!(tool.runtime(), "sh");
        assert!(!tool.is_linked());
        assert!(tool.manifest.created_at > 0);

        let got = store.get(&tool.id).expect("get").expect("present");
        assert_eq!(got, tool);
        assert_eq!(store.list().expect("list").len(), 1);

        // The starter script is written and readable.
        let body = store.read_script(&tool.id).expect("read");
        assert!(body.contains("hello from Greet"), "body was {body:?}");

        // Edit it, then read it back.
        store.write_script(&tool.id, "echo custom\n").expect("write");
        assert_eq!(store.read_script(&tool.id).expect("reread"), "echo custom\n");
    }

    #[test]
    fn owned_script_lands_at_the_runtime_extension() {
        let store = scratch("ext");
        let sh = store.create_file("s", None, "sh", None, None).expect("sh");
        assert!(store.script_path(&sh.id).expect("path").ends_with("script.sh"));
        let ts = store.create_file("t", None, "ts", None, None).expect("ts");
        assert!(store.script_path(&ts.id).expect("path").ends_with("script.ts"));
    }

    #[test]
    fn an_unknown_runtime_is_refused() {
        let store = scratch("badruntime");
        assert!(matches!(
            store.create_file("x", None, "perl", None, None),
            Err(Error::InvalidRuntime(_))
        ));
    }

    #[test]
    fn link_points_at_an_existing_file_and_infers_runtime() {
        let store = scratch("link");
        let dir = store.dir().join("external");
        std::fs::create_dir_all(&dir).expect("mkdir");
        let target = dir.join("build.ts");
        std::fs::write(&target, "console.log('x')\n").expect("write target");

        let tool = store
            .link(&target.to_string_lossy(), None, None, None, None)
            .expect("link");
        assert!(tool.is_linked());
        assert_eq!(tool.manifest.name, "build");
        assert_eq!(tool.runtime(), "ts");
        // Reads through to the linked file.
        assert_eq!(store.read_script(&tool.id).expect("read"), "console.log('x')\n");

        // Removing a linked tool never deletes the target file.
        assert!(store.remove(&tool.id).expect("remove"));
        assert!(target.exists(), "linked target must survive removal");
    }

    #[test]
    fn linking_a_missing_path_is_refused() {
        let store = scratch("linkmissing");
        assert!(matches!(
            store.link("/no/such/file-xyz", None, None, None, None),
            Err(Error::LinkedMissing(_))
        ));
    }

    #[test]
    fn archive_toggles_state_and_bin_shim() {
        let store = scratch("archive");
        let tool = store.create_file("deploy", None, "sh", None, None).expect("create");
        let shim = store.bin_dir().join("deploy");
        assert!(shim.exists(), "active tool should have a .bin shim");

        let archived = store.archive(&tool.id).expect("archive");
        assert!(archived.is_archived());
        assert!(!shim.exists(), "archived tool's shim should be gone");

        let restored = store.unarchive(&tool.id).expect("unarchive");
        assert!(!restored.is_archived());
        assert!(shim.exists(), "restored tool's shim should return");
    }

    #[test]
    fn bin_shim_delegates_to_the_cli_run() {
        let store = scratch("shim");
        let tool = store.create_file("My Tool", None, "sh", None, None).expect("create");
        let shim = store.bin_dir().join("my-tool");
        let body = std::fs::read_to_string(&shim).expect("shim");
        assert!(body.contains(&format!("adi-mono tools run {}", tool.id)), "shim: {body}");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt as _;
            let mode = std::fs::metadata(&shim).expect("meta").permissions().mode();
            assert_eq!(mode & 0o111, 0o111, "shim must be executable");
        }
    }

    #[test]
    fn colliding_bin_names_keep_the_lower_id() {
        let store = scratch("collide");
        // Two tools whose names slug to the same shim name.
        let a = store.create_file("Same Name", None, "sh", None, None).expect("a");
        let b = store.create_file("same-name", None, "sh", None, None).expect("b");
        let map = store.sync_bin().expect("sync");
        let winner = map.get("same-name").expect("a shim named same-name");
        let lower = std::cmp::min(a.id.clone(), b.id.clone());
        assert_eq!(winner, &lower, "lower id wins the shim");
    }

    #[test]
    fn seed_system_is_idempotent_and_flags_system_tools() {
        let store = scratch("seed");
        assert!(store.seed_system().expect("seed"), "first seed creates tools");
        assert!(!store.seed_system().expect("reseed"), "second seed is a no-op");
        let tools = store.list().expect("list");
        assert!(!tools.is_empty());
        assert!(tools.iter().all(|t| t.is_system()), "all seeded are system");
        // A known one wraps its adi-mono subcommand.
        let tasks = store.get("sys-tasks").expect("get").expect("present");
        assert!(tasks.is_system());
        assert_eq!(tasks.manifest.name, "adi-tasks");
        assert!(store.read_script("sys-tasks").expect("script").contains("adi-mono tasks"));
    }

    #[test]
    fn a_system_tool_cannot_be_hard_deleted() {
        let store = scratch("sysdel");
        store.seed_system().expect("seed");
        assert!(matches!(
            store.remove("sys-tasks"),
            Err(Error::SystemProtected(_))
        ));
        // But it can be archived (to disable it).
        assert!(store.archive("sys-tasks").expect("archive").is_archived());
    }

    #[test]
    fn agent_bin_holds_only_the_enabled_tools() {
        let store = scratch("agentbin");
        store.seed_system().expect("seed");
        let mine = store.create_file("mine", None, "sh", None, None).expect("mine");
        let other = store.create_file("other", None, "sh", None, None).expect("other");

        // Enable one user tool + one system tool; the other user tool is left off.
        let enabled = vec![mine.id.clone(), "sys-tasks".to_string()];
        let dir = store.sync_agent_bin("solver", &enabled).expect("agent bin");
        assert!(dir.ends_with(".agent-bin/solver"), "got {}", dir.display());
        assert!(dir.join("mine").exists(), "enabled user tool present");
        assert!(dir.join("adi-tasks").exists(), "enabled system tool present");
        assert!(!dir.join("other").exists(), "unselected tool absent");

        // An empty selection yields an empty bin (nothing force-fed).
        let empty = store.sync_agent_bin("bare", &[]).expect("empty");
        assert_eq!(std::fs::read_dir(&empty).expect("read").count(), 0);
        let _ = other;
    }

    #[test]
    fn run_executes_and_captures_output() {
        let store = scratch("run");
        let tool = store.create_file("echoer", None, "sh", None, None).expect("create");
        store
            .write_script(&tool.id, "printf 'ran:%s' \"$1\"\n")
            .expect("write");
        let out = store
            .run(&tool.id, &["ok".to_string()], None)
            .expect("run");
        assert!(out.ok());
        assert_eq!(out.output, "ran:ok");
    }

    #[test]
    fn mutating_an_unregistered_tool_is_not_found() {
        let store = scratch("missing");
        assert!(matches!(store.archive("ghost"), Err(Error::NotFound(_))));
        assert!(matches!(store.read_script("ghost"), Err(Error::NotFound(_))));
        assert!(store.get("ghost").expect("get").is_none());
        assert!(!store.remove("ghost").expect("remove missing"));
    }

    #[test]
    fn invalid_ids_never_touch_disk() {
        let store = scratch("invalid");
        assert!(matches!(store.get("../escape"), Err(Error::InvalidId(_))));
        assert!(matches!(store.remove(".."), Err(Error::InvalidId(_))));
        assert!(matches!(store.tool_dir("a/b"), Err(Error::InvalidId(_))));
    }

    #[test]
    fn list_skips_the_bin_dir_and_dirs_without_a_manifest() {
        let store = scratch("skip");
        store.create_file("real", None, "sh", None, None).expect("create");
        std::fs::create_dir_all(store.dir().join("bare")).expect("mkdir");
        let all = store.list().expect("list");
        assert_eq!(all.len(), 1, "only the real tool is listed");
        assert_eq!(all[0].manifest.name, "real");
    }
}
