/**
 * `@adi/db` — run SQL against the shared adi SQLite store, from Bun.
 *
 * The platform seeds this package into the mono store's own `node_modules`, and every `.ts` the
 * platform runs (a tool's `script.ts`, a dashboard's backend, a `ts` trigger) lives *under* that
 * store — so Bun's upward module resolution finds it with no install step:
 *
 * ```ts
 * import { query, run } from "@adi/db";
 *
 * run("create table if not exists notes (id integer primary key, body text, at integer)");
 * run("insert into notes (body, at) values (?, ?)", "hello", Date.now());
 * const recent = query<{ id: number; body: string }>("select * from notes order by at desc limit 5");
 * ```
 *
 * It talks to the same file as `adi-db` on the CLI — `bun:sqlite` and Rust's SQLite are the same
 * engine over the same bytes — so a table an agent creates in the shell is readable here, and vice
 * versa. Both sides open in WAL mode, which is what makes concurrent readers and a writer across
 * separate processes safe.
 *
 * Generated by the platform from `crates/adi-db/templates/client/index.ts`; local edits are
 * overwritten on the next start.
 */

import { Database } from "bun:sqlite";
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";

/** Which database to talk to: the global one by default, or a project's. */
export interface Scope {
  /** A project id — its own database under `db/projects/`. Omit for the global database. */
  project?: string | null;
  /** Open without write access. Reads never block on a writer, so this is cheap insurance. */
  readonly?: boolean;
}

/**
 * The pragmas every opener applies, on both sides of the platform. WAL is the important one: it
 * lets many processes read while one writes, which is exactly the shape of several agents, the
 * app, and a dashboard sharing one file. `busy_timeout` turns the remaining writer-vs-writer
 * contention into a short wait instead of an immediate `SQLITE_BUSY` error.
 *
 * **The order matters.** Setting `journal_mode` takes a lock, so on a connection with no timeout
 * yet it throws the moment another process is mid-write or recovering a WAL — opening while four
 * other writers are busy would fail before doing any work. `busy_timeout` goes first so that
 * statement waits its turn instead.
 */
const PRAGMAS = [
  "pragma busy_timeout = 5000",
  "pragma journal_mode = WAL",
  "pragma foreign_keys = ON",
  "pragma synchronous = NORMAL",
] as const;

/**
 * The mono store root — `$HOME/<$ADI_DIR>/mono`, where `ADI_DIR` defaults to `.adi`.
 *
 * `ADI_DIR` is a directory *name* under home, not a path to the store, which is why `mono` is
 * appended here. `resolve` rather than `join` because the Rust side builds this with
 * `PathBuf::join`, where an absolute segment replaces what came before it — tests and pinned
 * installs do set `ADI_DIR` to an absolute path, and both sides have to land on the same file.
 */
export function storeRoot(): string {
  const name = (process.env.ADI_DIR ?? "").trim() || ".adi";
  return resolve(homedir(), name, "mono");
}

/**
 * Where a scope's database file lives.
 *
 * With no project, `$ADI_DB` wins when set: the platform exports it into every agent, tool, and
 * trigger run already pointed at the right scope, so "the database" means the one this run was
 * launched for without the caller knowing whether it's global or a project's.
 */
export function dbPath(project?: string | null): string {
  if (!project) {
    return process.env.ADI_DB || join(storeRoot(), "db", "global.db");
  }

  // The id is about to become a path segment; reject anything that isn't one.
  if (project === "." || project === ".." || !/^[A-Za-z0-9._-]+$/.test(project)) {
    throw new Error(`invalid project id: ${JSON.stringify(project)}`);
  }

  return join(storeRoot(), "db", "projects", `${project}.db`);
}

/** Open a scope's database, creating the file (and `db/`) on first write-mode use. */
export function open(scope: Scope = {}): Database {
  const path = dbPath(scope.project);
  if (scope.readonly) {
    const db = new Database(path, { readonly: true });
    db.run("pragma busy_timeout = 5000");
    return db;
  }
  mkdirSync(dirname(path), { recursive: true });
  const db = new Database(path, { create: true });
  for (const pragma of PRAGMAS) db.run(pragma);
  return db;
}

/** The default connection — the scope this run was launched for. Opened once, on first use. */
let memo: Database | undefined;

/** The default connection, opened lazily so importing this module alone touches no disk. */
export function db(): Database {
  return (memo ??= open());
}

/** Close the default connection (and drop the memo, so a later call reopens it). */
export function close(): void {
  memo?.close();
  memo = undefined;
}

/** Every row a statement returns. Params are positional, bound to each `?`. */
export function query<T = Record<string, unknown>>(sql: string, ...params: unknown[]): T[] {
  return db().query(sql).all(...(params as never[])) as T[];
}

/** The first row a statement returns, or `null` when it returns none. */
export function get<T = Record<string, unknown>>(sql: string, ...params: unknown[]): T | null {
  return (db().query(sql).get(...(params as never[])) as T | undefined) ?? null;
}

/** Run a statement for its effect (`INSERT`/`UPDATE`/`DELETE`/DDL). */
export function run(sql: string, ...params: unknown[]): { changes: number; lastInsertRowid: number | bigint } {
  const result = db().run(sql, ...(params as never[]));
  return { changes: result.changes, lastInsertRowid: result.lastInsertRowid };
}

/** Run several statements in one go — DDL batches, migrations, a seed file. No parameters. */
export function exec(sql: string): void {
  db().run(sql);
}

/**
 * Run `fn` inside a transaction, committing on return and rolling back if it throws.
 *
 * The transaction is `BEGIN IMMEDIATE`, which takes the write lock up front. That matters with
 * more than one process on the file: a plain `BEGIN` starts out as a reader and has to *upgrade*
 * when the first write arrives, and if another process wrote in between, SQLite can only fail the
 * upgrade — `busy_timeout` cannot save it, because rolling back is the only legal move. Taking the
 * lock at the start turns that unrecoverable error back into an ordinary wait.
 */
export function tx<T>(fn: (db: Database) => T): T {
  const conn = db();
  conn.run("begin immediate");
  try {
    const out = fn(conn);
    conn.run("commit");
    return out;
  } catch (err) {
    try {
      conn.run("rollback");
    } catch {
      // The rollback failing (e.g. the transaction was already rolled back by SQLite) must not
      // mask the original error, which is the one the caller needs to see.
    }
    throw err;
  }
}

/** The tables and views in the default database, with their columns. */
export function tables(): { name: string; kind: string; sql: string }[] {
  return query<{ name: string; kind: string; sql: string }>(
    `select name, type as kind, coalesce(sql, '') as sql
       from sqlite_master
      where type in ('table', 'view') and name not like 'sqlite_%'
      order by name`,
  );
}
